-- ============================================================
-- Migration 006: Add subtopic column and generate SAT questions
-- Run this in Supabase SQL Editor
-- ============================================================

-- 1. Add subtopic column
ALTER TABLE sat_questions ADD COLUMN IF NOT EXISTS subtopic text;

-- 2. Index for efficient diagnostic queries
CREATE INDEX IF NOT EXISTS idx_sat_questions_subtopic ON sat_questions(subtopic);
CREATE INDEX IF NOT EXISTS idx_sat_questions_category_subtopic ON sat_questions(category, subtopic);

-- 3. Backfill existing questions with subtopics based on content heuristics
-- Algebra subtopics
UPDATE sat_questions SET subtopic = 'linear-equations' WHERE category = 'Algebra' AND subtopic IS NULL AND (question ILIKE '%linear%' OR question ILIKE '%slope%' OR question ILIKE '%y = mx%' OR question ILIKE '%y-intercept%') AND id IN (SELECT id FROM sat_questions WHERE category = 'Algebra' AND subtopic IS NULL LIMIT 20);
UPDATE sat_questions SET subtopic = 'quadratics' WHERE category = 'Algebra' AND subtopic IS NULL AND (question ILIKE '%quadratic%' OR question ILIKE '%factor%' OR question ILIKE '%x²%' OR question ILIKE '%parabola%') AND id IN (SELECT id FROM sat_questions WHERE category = 'Algebra' AND subtopic IS NULL LIMIT 20);
UPDATE sat_questions SET subtopic = 'systems-of-equations' WHERE category = 'Algebra' AND subtopic IS NULL AND (question ILIKE '%system%' OR question ILIKE '%simultaneous%' OR question ILIKE '%two equations%') AND id IN (SELECT id FROM sat_questions WHERE category = 'Algebra' AND subtopic IS NULL LIMIT 20);
UPDATE sat_questions SET subtopic = 'functions' WHERE category = 'Algebra' AND subtopic IS NULL AND (question ILIKE '%f(x)%' OR question ILIKE '%function%' OR question ILIKE '%domain%' OR question ILIKE '%range%') AND id IN (SELECT id FROM sat_questions WHERE category = 'Algebra' AND subtopic IS NULL LIMIT 20);
UPDATE sat_questions SET subtopic = 'inequalities' WHERE category = 'Algebra' AND subtopic IS NULL AND (question ILIKE '%inequalit%' OR question ILIKE '%greater than%' OR question ILIKE '%less than%') AND id IN (SELECT id FROM sat_questions WHERE category = 'Algebra' AND subtopic IS NULL LIMIT 20);
-- Catch remaining algebra questions
UPDATE sat_questions SET subtopic = 'linear-equations' WHERE category = 'Algebra' AND subtopic IS NULL;

-- Reading subtopics
UPDATE sat_questions SET subtopic = 'main-idea' WHERE category = 'Reading Comprehension' AND subtopic IS NULL AND (question ILIKE '%main idea%' OR question ILIKE '%central%' OR question ILIKE '%primarily%' OR question ILIKE '%purpose%') AND id IN (SELECT id FROM sat_questions WHERE category = 'Reading Comprehension' AND subtopic IS NULL LIMIT 25);
UPDATE sat_questions SET subtopic = 'vocabulary-in-context' WHERE category = 'Reading Comprehension' AND subtopic IS NULL AND (question ILIKE '%word%mean%' OR question ILIKE '%most nearly%' OR question ILIKE '%closest in meaning%' OR question ILIKE '%as used in%') AND id IN (SELECT id FROM sat_questions WHERE category = 'Reading Comprehension' AND subtopic IS NULL LIMIT 25);
UPDATE sat_questions SET subtopic = 'evidence-based' WHERE category = 'Reading Comprehension' AND subtopic IS NULL AND (question ILIKE '%evidence%' OR question ILIKE '%support%' OR question ILIKE '%best describes%' OR question ILIKE '%according to%') AND id IN (SELECT id FROM sat_questions WHERE category = 'Reading Comprehension' AND subtopic IS NULL LIMIT 25);
UPDATE sat_questions SET subtopic = 'inference' WHERE category = 'Reading Comprehension' AND subtopic IS NULL;

-- Grammar subtopics
UPDATE sat_questions SET subtopic = 'punctuation' WHERE category = 'Grammar' AND subtopic IS NULL AND (question ILIKE '%comma%' OR question ILIKE '%semicolon%' OR question ILIKE '%colon%' OR question ILIKE '%punctuat%' OR question ILIKE '%apostrophe%') AND id IN (SELECT id FROM sat_questions WHERE category = 'Grammar' AND subtopic IS NULL LIMIT 20);
UPDATE sat_questions SET subtopic = 'subject-verb-agreement' WHERE category = 'Grammar' AND subtopic IS NULL AND (question ILIKE '%verb%' OR question ILIKE '%tense%' OR question ILIKE '%agreement%' OR question ILIKE '%subject%') AND id IN (SELECT id FROM sat_questions WHERE category = 'Grammar' AND subtopic IS NULL LIMIT 20);
UPDATE sat_questions SET subtopic = 'sentence-structure' WHERE category = 'Grammar' AND subtopic IS NULL AND (question ILIKE '%sentence%' OR question ILIKE '%fragment%' OR question ILIKE '%run-on%' OR question ILIKE '%clause%' OR question ILIKE '%combine%') AND id IN (SELECT id FROM sat_questions WHERE category = 'Grammar' AND subtopic IS NULL LIMIT 20);
UPDATE sat_questions SET subtopic = 'transitions' WHERE category = 'Grammar' AND subtopic IS NULL AND (question ILIKE '%transition%' OR question ILIKE '%however%' OR question ILIKE '%therefore%' OR question ILIKE '%logical%' OR question ILIKE '%connect%') AND id IN (SELECT id FROM sat_questions WHERE category = 'Grammar' AND subtopic IS NULL LIMIT 20);
UPDATE sat_questions SET subtopic = 'pronoun-clarity' WHERE category = 'Grammar' AND subtopic IS NULL;

-- Data & Statistics subtopics
UPDATE sat_questions SET subtopic = 'tables-and-graphs' WHERE category = 'Data & Statistics' AND subtopic IS NULL AND (question ILIKE '%table%' OR question ILIKE '%graph%' OR question ILIKE '%chart%' OR question ILIKE '%bar%' OR question ILIKE '%display%') AND id IN (SELECT id FROM sat_questions WHERE category = 'Data & Statistics' AND subtopic IS NULL LIMIT 25);
UPDATE sat_questions SET subtopic = 'probability' WHERE category = 'Data & Statistics' AND subtopic IS NULL AND (question ILIKE '%probabilit%' OR question ILIKE '%chance%' OR question ILIKE '%likely%' OR question ILIKE '%random%') AND id IN (SELECT id FROM sat_questions WHERE category = 'Data & Statistics' AND subtopic IS NULL LIMIT 25);
UPDATE sat_questions SET subtopic = 'scatterplots' WHERE category = 'Data & Statistics' AND subtopic IS NULL AND (question ILIKE '%scatter%' OR question ILIKE '%correlation%' OR question ILIKE '%best fit%' OR question ILIKE '%trend%' OR question ILIKE '%regression%') AND id IN (SELECT id FROM sat_questions WHERE category = 'Data & Statistics' AND subtopic IS NULL LIMIT 25);
UPDATE sat_questions SET subtopic = 'mean-median-mode' WHERE category = 'Data & Statistics' AND subtopic IS NULL;

-- ============================================================
-- 4. Generate new questions for each subtopic
-- Target: ~10 per subtopic per difficulty = ~540 new questions
-- ============================================================

-- ===================== ALGEBRA =====================

-- Linear Equations
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Algebra', 'easy', 'linear-equations', 'Solve for x: 2x + 6 = 14', 'x = 3', 'x = 4', 'x = 5', 'x = 8', 'B', 'Subtract 6 from both sides: 2x = 8. Divide by 2: x = 4.'),
('Algebra', 'easy', 'linear-equations', 'What is the slope of the line y = 3x - 7?', '3', '-7', '7', '-3', 'A', 'In y = mx + b form, the slope m is the coefficient of x, which is 3.'),
('Algebra', 'easy', 'linear-equations', 'If 5x = 35, what is x?', '5', '6', '7', '8', 'C', 'Divide both sides by 5: x = 35/5 = 7.'),
('Algebra', 'easy', 'linear-equations', 'What is the y-intercept of y = -2x + 9?', '-2', '9', '0', '-9', 'B', 'In y = mx + b form, the y-intercept is b = 9.'),
('Algebra', 'easy', 'linear-equations', 'Solve: x - 4 = 11', 'x = 7', 'x = 15', 'x = -7', 'x = -15', 'B', 'Add 4 to both sides: x = 11 + 4 = 15.'),
('Algebra', 'medium', 'linear-equations', 'A line passes through (2, 5) and (4, 11). What is its slope?', '2', '3', '6', '8', 'B', 'Slope = (11 - 5)/(4 - 2) = 6/2 = 3.'),
('Algebra', 'medium', 'linear-equations', 'Solve for x: 3(x - 2) = 2x + 7', 'x = 13', 'x = 11', 'x = 7', 'x = 1', 'A', 'Distribute: 3x - 6 = 2x + 7. Subtract 2x: x - 6 = 7. Add 6: x = 13.'),
('Algebra', 'medium', 'linear-equations', 'What is the equation of a line with slope 4 passing through (1, 3)?', 'y = 4x - 1', 'y = 4x + 3', 'y = 4x + 1', 'y = 3x + 4', 'A', 'Using point-slope: y - 3 = 4(x - 1) → y = 4x - 4 + 3 → y = 4x - 1.'),
('Algebra', 'hard', 'linear-equations', 'Line ℓ passes through (-1, 4) and is perpendicular to y = (1/3)x + 2. What is the equation of ℓ?', 'y = -3x + 1', 'y = -3x - 1', 'y = 3x + 7', 'y = (1/3)x + 5', 'A', 'Perpendicular slope = -3. Using point-slope: y - 4 = -3(x + 1) → y = -3x - 3 + 4 → y = -3x + 1.'),
('Algebra', 'hard', 'linear-equations', 'For what value of k does the line kx + 3y = 12 have a slope of -2?', '6', '4', '2', '-6', 'A', 'Rewrite: 3y = -kx + 12 → y = (-k/3)x + 4. Slope = -k/3 = -2 → k = 6.');

-- Systems of Equations
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Algebra', 'easy', 'systems-of-equations', 'Solve: x + y = 10 and x - y = 4. What is x?', '3', '5', '7', '14', 'C', 'Add the equations: 2x = 14, so x = 7.'),
('Algebra', 'easy', 'systems-of-equations', 'If x + y = 8 and y = 3, what is x?', '3', '5', '8', '11', 'B', 'Substitute y = 3: x + 3 = 8, so x = 5.'),
('Algebra', 'easy', 'systems-of-equations', 'Which point satisfies both y = x + 1 and y = 3?', '(2, 3)', '(3, 2)', '(1, 3)', '(4, 3)', 'A', 'If y = 3, then 3 = x + 1, so x = 2. The point is (2, 3).'),
('Algebra', 'medium', 'systems-of-equations', 'Solve: 2x + 3y = 12 and x - y = 1. What is y?', '1', '2', '3', '4', 'B', 'From equation 2: x = y + 1. Substitute: 2(y + 1) + 3y = 12 → 5y + 2 = 12 → y = 2.'),
('Algebra', 'medium', 'systems-of-equations', 'A system of equations has no solution. What must be true about the lines?', 'They are parallel', 'They are perpendicular', 'They are the same line', 'They intersect at one point', 'A', 'No solution means the lines never intersect — they are parallel (same slope, different intercepts).'),
('Algebra', 'medium', 'systems-of-equations', 'If 3x + 2y = 16 and x + 2y = 8, what is x?', '2', '4', '6', '8', 'B', 'Subtract the second equation from the first: 2x = 8, so x = 4.'),
('Algebra', 'hard', 'systems-of-equations', 'For the system 2x + ky = 6 and kx + 8y = 12 to have infinitely many solutions, what is k?', '2', '4', '6', '8', 'B', 'Infinitely many solutions means the equations are proportional: 2/k = k/8 = 6/12. From 6/12 = 1/2, we need 2/k = 1/2, so k = 4.'),
('Algebra', 'hard', 'systems-of-equations', 'At a store, 3 notebooks and 2 pens cost $13. 5 notebooks and 4 pens cost $23. What is the cost of one notebook?', '$2', '$3', '$4', '$5', 'B', 'Let n = notebook, p = pen. 3n + 2p = 13, 5n + 4p = 23. Multiply first by 2: 6n + 4p = 26. Subtract: n = 3.');

-- Quadratics
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Algebra', 'easy', 'quadratics', 'Factor: x² + 5x + 6', '(x + 1)(x + 6)', '(x + 2)(x + 3)', '(x + 3)(x + 3)', '(x - 2)(x - 3)', 'B', 'Find two numbers that multiply to 6 and add to 5: 2 and 3. So (x + 2)(x + 3).'),
('Algebra', 'easy', 'quadratics', 'What are the solutions of x² - 9 = 0?', 'x = 3 only', 'x = -3 only', 'x = 3 or x = -3', 'x = 9', 'C', 'x² = 9, so x = ±3.'),
('Algebra', 'easy', 'quadratics', 'What is the vertex of y = (x - 3)² + 1?', '(3, 1)', '(-3, 1)', '(1, 3)', '(3, -1)', 'A', 'In vertex form y = (x - h)² + k, the vertex is (h, k) = (3, 1).'),
('Algebra', 'medium', 'quadratics', 'Solve x² - 5x + 6 = 0', 'x = 1, x = 6', 'x = 2, x = 3', 'x = -2, x = -3', 'x = -1, x = -6', 'B', 'Factor: (x - 2)(x - 3) = 0, so x = 2 or x = 3.'),
('Algebra', 'medium', 'quadratics', 'If the graph of y = x² + bx + 5 has its vertex at x = -3, what is b?', '-6', '-3', '3', '6', 'D', 'Vertex x-coordinate = -b/2. So -b/2 = -3, meaning b = 6.'),
('Algebra', 'medium', 'quadratics', 'How many real solutions does x² + 4x + 5 = 0 have?', '0', '1', '2', 'Infinitely many', 'A', 'Discriminant = 16 - 20 = -4 < 0. No real solutions.'),
('Algebra', 'hard', 'quadratics', 'If one root of 2x² - 7x + k = 0 is 2, what is k?', '3', '5', '6', '10', 'C', 'Substitute x = 2: 2(4) - 7(2) + k = 0 → 8 - 14 + k = 0 → k = 6.'),
('Algebra', 'hard', 'quadratics', 'The equation x² - 6x + c = 0 has exactly one solution. What is c?', '6', '9', '12', '36', 'B', 'One solution means discriminant = 0. b² - 4ac = 36 - 4c = 0, so c = 9.');

-- Functions
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Algebra', 'easy', 'functions', 'If f(x) = 2x + 3, what is f(4)?', '8', '11', '14', '7', 'B', 'f(4) = 2(4) + 3 = 8 + 3 = 11.'),
('Algebra', 'easy', 'functions', 'If g(x) = x² - 1, what is g(3)?', '6', '8', '10', '4', 'B', 'g(3) = 3² - 1 = 9 - 1 = 8.'),
('Algebra', 'easy', 'functions', 'Which input gives f(x) = 0 if f(x) = x - 5?', '0', '5', '-5', '10', 'B', 'Set x - 5 = 0, so x = 5.'),
('Algebra', 'medium', 'functions', 'If f(x) = 3x - 1 and g(x) = x + 4, what is f(g(2))?', '11', '14', '17', '20', 'C', 'g(2) = 6. f(6) = 3(6) - 1 = 17.'),
('Algebra', 'medium', 'functions', 'The function f(x) = |x - 3| + 2 has a minimum value of:', '0', '2', '3', '5', 'B', 'The absolute value is always ≥ 0, so the minimum is 0 + 2 = 2, occurring at x = 3.'),
('Algebra', 'hard', 'functions', 'If f(x) = 2x + 1 and f(g(x)) = 6x - 3, what is g(x)?', '3x - 2', '3x + 1', '3x - 1', '6x - 4', 'A', 'f(g(x)) = 2g(x) + 1 = 6x - 3. So 2g(x) = 6x - 4, meaning g(x) = 3x - 2.'),
('Algebra', 'hard', 'functions', 'If f(x) = x² and g(x) = √(x + 4), what is the domain of g(f(x))?', 'All real numbers', 'x ≥ 0', 'x ≥ -2', 'x ≥ -4', 'A', 'g(f(x)) = √(x² + 4). Since x² ≥ 0, x² + 4 ≥ 4 > 0 always. Domain is all reals.');

-- Inequalities
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Algebra', 'easy', 'inequalities', 'Solve: x + 3 > 7', 'x > 4', 'x > 10', 'x < 4', 'x > 3', 'A', 'Subtract 3 from both sides: x > 4.'),
('Algebra', 'easy', 'inequalities', 'Which value satisfies 2x ≤ 10?', 'x = 6', 'x = 5', 'x = 11', 'x = 7', 'B', '2(5) = 10 ≤ 10 ✓. The others give values > 10.'),
('Algebra', 'easy', 'inequalities', 'Solve: -x < 3', 'x > -3', 'x < -3', 'x > 3', 'x < 3', 'A', 'Multiply both sides by -1 (flip the sign): x > -3.'),
('Algebra', 'medium', 'inequalities', 'Solve: 3x - 5 ≥ 2x + 1', 'x ≥ 6', 'x ≥ 4', 'x ≤ 6', 'x ≥ -6', 'A', 'Subtract 2x: x - 5 ≥ 1. Add 5: x ≥ 6.'),
('Algebra', 'medium', 'inequalities', 'Which inequality represents "a number decreased by 4 is at most 12"?', 'x - 4 ≤ 12', 'x - 4 ≥ 12', 'x - 4 < 12', '4 - x ≤ 12', 'A', '"At most" means ≤. A number (x) decreased by 4 gives x - 4 ≤ 12.'),
('Algebra', 'hard', 'inequalities', 'Solve: |2x - 3| < 5', '-1 < x < 4', 'x < -1 or x > 4', '-4 < x < 1', 'x > -1', 'A', '-5 < 2x - 3 < 5. Add 3: -2 < 2x < 8. Divide by 2: -1 < x < 4.'),
('Algebra', 'hard', 'inequalities', 'If -3 < 2x + 1 ≤ 9, which describes x?', '-2 < x ≤ 4', '-1 < x ≤ 5', '-2 ≤ x < 4', '-1 ≤ x < 5', 'A', 'Subtract 1: -4 < 2x ≤ 8. Divide by 2: -2 < x ≤ 4.');

-- ===================== READING COMPREHENSION =====================

-- Main Idea
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Reading Comprehension', 'easy', 'main-idea', 'A passage describes how honeybees communicate food locations through "waggle dances." The main purpose of this passage is to:', 'Argue that bees are more intelligent than other insects', 'Explain a method bees use to share information', 'Compare different species of bees', 'Describe the life cycle of a honeybee', 'B', 'The passage focuses on explaining the waggle dance as a communication method.'),
('Reading Comprehension', 'easy', 'main-idea', 'An article discusses the history of public libraries in America, from Benjamin Franklin''s subscription library to modern free libraries. The central idea is:', 'Libraries should receive more government funding', 'Public libraries evolved to become more accessible over time', 'Benjamin Franklin was the most important American inventor', 'Modern libraries are better than historical ones', 'B', 'The passage traces the evolution of libraries toward greater public access.'),
('Reading Comprehension', 'easy', 'main-idea', 'A passage describes how recycling plastic bottles reduces landfill waste and saves energy. What is the primary purpose?', 'To criticize companies that produce plastic', 'To explain the benefits of recycling plastic', 'To compare plastic with glass bottles', 'To argue for banning all plastics', 'B', 'The passage focuses on explaining why recycling plastic is beneficial.'),
('Reading Comprehension', 'medium', 'main-idea', 'A passage argues that standardized testing fails to measure creativity, collaboration, and critical thinking — skills essential for modern careers. The author''s central claim is:', 'Standardized tests should be made harder', 'Current testing methods are incomplete measures of student ability', 'Schools should eliminate all forms of assessment', 'Students perform poorly because they don''t study', 'B', 'The author argues tests miss key skills, making them incomplete measures.'),
('Reading Comprehension', 'medium', 'main-idea', 'A scientific article describes how coral reefs support biodiversity, protect coastlines, and provide economic value through tourism. Which best describes the passage''s organization?', 'Chronological order of reef development', 'Problem and proposed solution', 'Multiple benefits supporting a central thesis', 'Comparison of different reef types', 'C', 'The passage presents multiple benefits to support the thesis that coral reefs are valuable.'),
('Reading Comprehension', 'hard', 'main-idea', 'A historian writes: "The Renaissance is often portrayed as a sudden flowering of art and intellect, but this narrative ignores centuries of gradual progress during the medieval period." The author''s primary purpose is to:', 'Celebrate Renaissance achievements', 'Challenge a commonly held view about the Renaissance', 'Argue that medieval art was superior', 'Explain why the Renaissance occurred in Italy', 'B', 'The author challenges the "sudden flowering" narrative by pointing to gradual medieval progress.'),
('Reading Comprehension', 'hard', 'main-idea', 'An essay discusses how confirmation bias affects scientific research, political opinions, and everyday decisions. The author concludes that awareness of this bias is the first step toward better reasoning. The passage primarily serves to:', 'Prove that all scientific research is flawed', 'Illustrate a cognitive bias and advocate for self-awareness', 'Argue that political opinions are always irrational', 'Compare different types of cognitive biases', 'B', 'The passage illustrates confirmation bias across domains and argues for awareness as a remedy.');

-- Evidence-Based
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Reading Comprehension', 'easy', 'evidence-based', 'A passage states: "Solar panels have become 90% cheaper since 2010." This evidence best supports which claim?', 'Solar energy is now more affordable', 'Solar panels last longer than before', 'More homes have solar panels', 'Solar energy is the best energy source', 'A', 'A 90% cost reduction directly supports the claim that solar energy is more affordable.'),
('Reading Comprehension', 'easy', 'evidence-based', 'An author writes that exercise improves mental health. Which evidence would best support this claim?', 'Many gyms have opened recently', 'Studies show exercise releases endorphins that reduce anxiety', 'Athletes earn high salaries', 'Exercise equipment sales have increased', 'B', 'Scientific studies showing a biological mechanism (endorphins) directly support the mental health claim.'),
('Reading Comprehension', 'medium', 'evidence-based', '"The town''s population grew 40% after the new factory opened, and housing prices doubled within two years." Which conclusion does this evidence best support?', 'The factory caused environmental problems', 'Economic opportunities attract population growth', 'Housing is too expensive in the town', 'The factory should be relocated', 'B', 'Population growth following job creation supports the link between economic opportunity and migration.'),
('Reading Comprehension', 'medium', 'evidence-based', 'A researcher claims that sleep deprivation impairs driving ability as much as alcohol. Which evidence best supports this?', 'Many accidents occur at night', 'Studies show 24 hours without sleep produces impairment equal to 0.10% BAC', 'Tired drivers report feeling sleepy', 'Some countries ban driving at night', 'B', 'A direct comparison study with measurable impairment levels provides the strongest evidence.'),
('Reading Comprehension', 'hard', 'evidence-based', 'An author argues that ancient Rome''s decline was primarily economic, not military. Which evidence would most WEAKEN this argument?', 'Rome''s currency was debased by 80% over two centuries', 'Trade routes were disrupted by barbarian invasions', 'Military defeats at Adrianople preceded the economic collapse', 'Roman taxes increased in the final century', 'C', 'If military defeats came BEFORE economic collapse, this weakens the claim that economics was the primary cause.'),
('Reading Comprehension', 'hard', 'evidence-based', 'A passage presents two studies: Study A found that bilingual children scored higher on cognitive tests; Study B found no difference when controlling for socioeconomic status. Together, these studies suggest:', 'Bilingualism definitely improves cognition', 'The cognitive advantage may be explained by socioeconomic factors', 'Study A is more reliable than Study B', 'Socioeconomic status has no effect on cognition', 'B', 'When Study B eliminates the advantage by controlling for SES, it suggests SES may be the real factor.');

-- Vocabulary in Context
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Reading Comprehension', 'easy', 'vocabulary-in-context', '"The scientist conducted a rigorous experiment." As used here, "rigorous" most nearly means:', 'Difficult', 'Thorough and careful', 'Quick', 'Expensive', 'B', 'In a scientific context, "rigorous" means thorough, precise, and carefully controlled.'),
('Reading Comprehension', 'easy', 'vocabulary-in-context', '"The company adopted a novel approach to marketing." As used here, "novel" most nearly means:', 'Related to books', 'New and innovative', 'Complicated', 'Traditional', 'B', 'In this context, "novel" means new and original, not related to fiction.'),
('Reading Comprehension', 'medium', 'vocabulary-in-context', '"The politician''s remarks were calculated to appeal to undecided voters." As used here, "calculated" most nearly means:', 'Mathematical', 'Deliberately planned', 'Accidental', 'Risky', 'B', '"Calculated" here means intentionally designed or strategically planned.'),
('Reading Comprehension', 'medium', 'vocabulary-in-context', '"The author''s tone was measured throughout the essay, never veering into emotion." As used here, "measured" most nearly means:', 'Quantified', 'Restrained and deliberate', 'Uncertain', 'Lengthy', 'B', '"Measured" describes a controlled, careful tone — not the act of measuring something.'),
('Reading Comprehension', 'hard', 'vocabulary-in-context', '"The ambassador''s overture was met with suspicion by the opposing delegation." As used here, "overture" most nearly means:', 'Musical composition', 'Initial approach or proposal', 'Criticism', 'Formal apology', 'B', 'In diplomacy, an "overture" is an opening move or initial proposal, borrowing from the musical term for an opening piece.'),
('Reading Comprehension', 'hard', 'vocabulary-in-context', '"The artist''s work was animated by a restless curiosity about the natural world." As used here, "animated" most nearly means:', 'Made into a cartoon', 'Given life and energy', 'Presented publicly', 'Criticized', 'B', '"Animated" here means enlivened or given vitality — the curiosity drove and energized the work.');

-- Inference
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Reading Comprehension', 'easy', 'inference', '"Maria packed her umbrella, raincoat, and waterproof boots before leaving." What can you infer?', 'Maria likes collecting rain gear', 'Maria expected rain', 'It was already raining', 'Maria was going to work', 'B', 'Packing rain gear suggests she anticipated rain, though it hadn''t necessarily started yet.'),
('Reading Comprehension', 'easy', 'inference', '"After the announcement, employees exchanged worried glances and spoke in hushed tones." You can infer that:', 'The announcement was good news', 'The employees were confused by the announcement', 'The announcement was concerning or bad news', 'The employees didn''t hear the announcement', 'C', 'Worried glances and hushed tones indicate the news was concerning.'),
('Reading Comprehension', 'medium', 'inference', '"The restaurant, once packed every evening, now had more staff than customers on a Saturday night." What can be inferred?', 'The restaurant raised its prices', 'The restaurant''s popularity has declined', 'It was a holiday weekend', 'The staff was recently hired', 'B', 'The contrast between "once packed" and "more staff than customers" implies declining popularity.'),
('Reading Comprehension', 'medium', 'inference', '"Despite receiving the highest funding of any department, the research team produced fewer publications than any other group." This suggests:', 'The research is too difficult', 'There may be inefficiency in how the funding is used', 'The team needs even more funding', 'Publications are not important', 'B', 'High input (funding) with low output (publications) suggests inefficiency.'),
('Reading Comprehension', 'hard', 'inference', '"The author notes that while literacy rates in the region have improved from 40% to 85% over two decades, the number of independent bookstores has halved." This juxtaposition implies:', 'People read fewer books despite being more literate', 'Literacy rates were measured incorrectly', 'Bookstores are unnecessary', 'The author supports digital reading', 'A', 'The contrast between rising literacy and declining bookstores suggests literacy hasn''t translated to more book buying — possibly due to digital alternatives.'),
('Reading Comprehension', 'hard', 'inference', '"The candidate spoke passionately about reform but voted against every reform bill in the past decade." The author most likely includes this detail to:', 'Show the candidate''s evolution on reform', 'Highlight a contradiction between words and actions', 'Argue that reform bills are poorly written', 'Suggest the candidate will change their voting pattern', 'B', 'The contrast between rhetoric and voting record highlights hypocrisy or inconsistency.');

-- ===================== GRAMMAR =====================

-- Sentence Structure
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Grammar', 'easy', 'sentence-structure', 'Which is a complete sentence?', 'Running through the park on a sunny day.', 'She runs every morning before work.', 'Although he finished the race.', 'The tall building with the red door.', 'B', 'Only B has a subject (She) and a complete predicate (runs every morning before work).'),
('Grammar', 'easy', 'sentence-structure', 'Which correctly combines these sentences: "The dog barked. The cat ran away."', 'The dog barked, the cat ran away.', 'The dog barked, and the cat ran away.', 'The dog barked and the cat ran away.', 'The dog barked the cat ran away.', 'B', 'Two independent clauses joined by a comma + coordinating conjunction (and) is correct.'),
('Grammar', 'easy', 'sentence-structure', 'Identify the sentence fragment:', 'We went to the store.', 'Because it was raining outside.', 'The movie was exciting.', 'She read the entire book.', 'B', '"Because it was raining outside" is a dependent clause — it can''t stand alone as a sentence.'),
('Grammar', 'medium', 'sentence-structure', 'Which revision best fixes this run-on: "The experiment failed the researchers tried again"?', 'The experiment failed, the researchers tried again.', 'The experiment failed; the researchers tried again.', 'The experiment failed the researchers, tried again.', 'The experiment, failed the researchers tried again.', 'B', 'A semicolon correctly separates two related independent clauses.'),
('Grammar', 'medium', 'sentence-structure', '"The students, having completed the assignment early, were allowed to leave." The underlined phrase is a:', 'Independent clause', 'Participial phrase', 'Prepositional phrase', 'Infinitive phrase', 'B', '"Having completed the assignment early" is a participial phrase modifying "students."'),
('Grammar', 'hard', 'sentence-structure', 'Which sentence uses parallel structure correctly?', 'She likes hiking, swimming, and to ride bikes.', 'She likes hiking, swimming, and riding bikes.', 'She likes to hike, swimming, and bike riding.', 'She likes hiking, to swim, and riding bikes.', 'B', 'Parallel structure requires matching forms: hiking, swimming, and riding (all gerunds).'),
('Grammar', 'hard', 'sentence-structure', '"Not only did the team win the championship, but they also set a new record." This sentence structure is:', 'A compound sentence with a comma splice', 'A correlative conjunction construction', 'A sentence fragment', 'A run-on sentence', 'B', '"Not only...but also" is a correlative conjunction pair, correctly used here.');

-- Punctuation
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Grammar', 'easy', 'punctuation', 'Which sentence uses commas correctly?', 'The tall, dark, and handsome man walked in.', 'The tall dark, and, handsome man walked in.', 'The tall dark and, handsome man walked in.', 'The, tall dark and handsome, man walked in.', 'A', 'Commas separate items in a list of adjectives: tall, dark, and handsome.'),
('Grammar', 'easy', 'punctuation', 'Which sentence is punctuated correctly?', 'Its a beautiful day outside.', 'Its'' a beautiful day outside.', 'It''s a beautiful day outside.', 'Its, a beautiful day outside.', 'C', '"It''s" is the contraction of "it is." "Its" (no apostrophe) is the possessive form.'),
('Grammar', 'medium', 'punctuation', 'Which sentence correctly uses a semicolon?', 'The weather was cold; and rainy.', 'I love reading; it expands my worldview.', 'She went to the store; bought milk.', 'The dog; barked loudly.', 'B', 'A semicolon connects two related independent clauses. Only B has two complete clauses.'),
('Grammar', 'medium', 'punctuation', 'Which sentence correctly uses a colon?', 'She brought: apples, oranges, and grapes.', 'She brought three items: apples, oranges, and grapes.', 'She: brought apples, oranges, and grapes.', 'She brought three items apples: oranges, and grapes.', 'B', 'A colon follows a complete sentence and introduces a list. Only B has a complete clause before the colon.'),
('Grammar', 'hard', 'punctuation', '"The research — which took over three years — finally produced results." The dashes in this sentence serve to:', 'Indicate a pause for dramatic effect', 'Set off a nonessential parenthetical element', 'Show the speaker is interrupted', 'Separate items in a list', 'B', 'Dashes (like commas or parentheses) can set off nonessential information that could be removed.'),
('Grammar', 'hard', 'punctuation', 'Which is correct? "The students'' grades improved after the teachers'' workshop."', 'Both apostrophes are correct', 'Both apostrophes are incorrect', 'Only the first apostrophe is correct', 'Only the second apostrophe is correct', 'A', 'Both are plural possessives: the grades belonging to multiple students, the workshop belonging to multiple teachers.');

-- Subject-Verb Agreement
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Grammar', 'easy', 'subject-verb-agreement', 'Which sentence has correct subject-verb agreement?', 'The dogs runs in the park.', 'The dogs run in the park.', 'The dogs is running in the park.', 'The dogs has run in the park.', 'B', 'Plural subject "dogs" requires plural verb "run."'),
('Grammar', 'easy', 'subject-verb-agreement', 'Choose the correct sentence:', 'She don''t like pizza.', 'She doesn''t likes pizza.', 'She doesn''t like pizza.', 'She don''t likes pizza.', 'C', 'Third person singular "she" takes "doesn''t" + base verb "like."'),
('Grammar', 'medium', 'subject-verb-agreement', '"The group of students ___ ready for the test." Choose the correct verb:', 'are', 'is', 'were', 'have been', 'B', 'The subject is "group" (singular), not "students." A singular subject takes "is."'),
('Grammar', 'medium', 'subject-verb-agreement', '"Neither the teacher nor the students ___ aware of the change." Choose the correct verb:', 'was', 'is', 'were', 'has been', 'C', 'With "neither...nor," the verb agrees with the nearest subject — "students" (plural), so "were."'),
('Grammar', 'hard', 'subject-verb-agreement', '"The data from the experiments ___ the hypothesis." Choose the correct verb:', 'supports', 'support', 'is supporting', 'has supported', 'B', '"Data" is technically plural (singular: datum), so it takes "support." In formal academic writing, "data" is treated as plural.'),
('Grammar', 'hard', 'subject-verb-agreement', '"Every one of the books on the shelf ___ been read." Choose the correct verb:', 'have', 'has', 'are', 'were', 'B', '"Every one" is singular, so it takes "has." The prepositional phrase "of the books" doesn''t change the subject.');

-- Pronoun Clarity
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Grammar', 'easy', 'pronoun-clarity', 'Which sentence has a clear pronoun reference?', 'When John met Bob, he was happy.', 'When John met Bob, John was happy.', 'When John met Bob, they was happy.', 'When John met Bob, him was happy.', 'B', 'In A, "he" is ambiguous — it could mean John or Bob. B clarifies by repeating "John."'),
('Grammar', 'easy', 'pronoun-clarity', 'Choose the correct pronoun: "Each student must bring ___ own textbook."', 'their', 'his or her', 'its', 'they', 'B', '"Each student" is singular and refers to people, so "his or her" is formally correct. ("Their" is increasingly accepted in modern usage.)'),
('Grammar', 'medium', 'pronoun-clarity', '"The company announced that they would be closing the office." What is the error?', 'No error', '"they" should be "it" (company is singular)', '"would" should be "will"', '"closing" should be "closed"', 'B', '"Company" is singular and should be referred to as "it," not "they."'),
('Grammar', 'medium', 'pronoun-clarity', '"Sarah told Emma that her presentation was excellent." The pronoun "her" is ambiguous because:', 'It could refer to Sarah or Emma', 'It''s the wrong case', 'It should be "hers"', 'There is no ambiguity', 'A', '"Her" could refer to either Sarah''s or Emma''s presentation. The sentence should clarify whose.'),
('Grammar', 'hard', 'pronoun-clarity', '"The committee submitted their report, but it was rejected because they failed to include the data." How many pronoun errors are there?', '0', '1', '2', '3', 'B', '"Committee" is singular, so "their" should be "its." However, "they" later is also questionable — the sentence needs revision for consistency. The primary error is "their."');

-- Transitions
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Grammar', 'easy', 'transitions', '"She studied hard for the exam. ___, she earned an A." Choose the best transition:', 'However', 'Therefore', 'Meanwhile', 'Instead', 'B', '"Therefore" shows cause and effect — studying hard led to earning an A.'),
('Grammar', 'easy', 'transitions', '"I wanted to go outside. ___, it was raining." Choose the best transition:', 'Furthermore', 'However', 'Therefore', 'In addition', 'B', '"However" introduces a contrast — wanting to go outside versus the obstacle of rain.'),
('Grammar', 'medium', 'transitions', '"The first experiment yielded no results. ___, the team redesigned their approach and ran a second trial." Choose the best transition:', 'Similarly', 'In other words', 'Consequently', 'For example', 'C', '"Consequently" shows that the redesign was a direct result of the first experiment''s failure.'),
('Grammar', 'medium', 'transitions', '"The novel explores themes of isolation; ___, the protagonist rarely interacts with other characters." Choose the best transition:', 'however', 'indeed', 'nevertheless', 'otherwise', 'B', '"Indeed" reinforces the previous statement — the character''s lack of interaction confirms the theme of isolation.'),
('Grammar', 'hard', 'transitions', '"Critics praised the film for its visual effects. ___, they noted that the plot was predictable and the dialogue was weak." Choose the best transition:', 'Moreover', 'Nonetheless', 'In particular', 'Likewise', 'B', '"Nonetheless" signals a concession — despite praising the visuals, critics found other flaws.'),
('Grammar', 'hard', 'transitions', '"The study found a correlation between sleep and academic performance. ___, students who slept 8 hours scored 20% higher on exams." Choose the best transition:', 'In contrast', 'Specifically', 'Nevertheless', 'On the other hand', 'B', '"Specifically" introduces a concrete example that supports the general finding.');

-- ===================== DATA & STATISTICS =====================

-- Tables and Graphs
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'easy', 'tables-and-graphs', 'A bar graph shows sales: Jan=100, Feb=150, Mar=200, Apr=175. Which month had the highest sales?', 'January', 'February', 'March', 'April', 'C', 'March had the highest sales at 200.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A table shows: Class A has 25 students, Class B has 30 students, Class C has 22 students. How many total students?', '52', '55', '67', '77', 'D', '25 + 30 + 22 = 77 total students.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A pie chart shows: 40% prefer pizza, 30% prefer burgers, 20% prefer tacos, 10% prefer salad. If 200 people were surveyed, how many prefer pizza?', '40', '60', '80', '100', 'C', '40% of 200 = 0.40 × 200 = 80 people.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A double bar graph compares test scores for boys and girls across 4 subjects. Boys scored higher in Math and Science; girls scored higher in English and History. Which conclusion is supported?', 'Boys are smarter than girls', 'Performance varies by subject and gender', 'The test was unfair', 'Girls study harder than boys', 'B', 'The data only shows variation by subject — no conclusion about intelligence or effort is supported.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A line graph shows a company''s revenue increasing from $1M to $5M over 5 years, but the y-axis starts at $900K instead of $0. This makes the growth appear:', 'Smaller than it actually is', 'Larger than it actually is', 'Exactly accurate', 'Negative', 'B', 'Starting the y-axis above zero (a broken axis) exaggerates the visual appearance of growth.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A table shows survey results by age group. 18-25: 60% support, 26-40: 45% support, 41-60: 35% support, 60+: 25% support. A claim states "most people support the policy." Is this claim supported?', 'Yes, because the youngest group shows 60%', 'No, because the overall support depends on group sizes', 'Yes, because all groups show some support', 'No, because 25% is very low', 'B', 'Without knowing the size of each age group, we can''t calculate overall support. The largest group might be the least supportive.');

-- Probability
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'easy', 'probability', 'A bag contains 3 red balls and 7 blue balls. What is the probability of drawing a red ball?', '3/7', '3/10', '7/10', '1/3', 'B', 'P(red) = favorable/total = 3/(3+7) = 3/10.'),
('Data & Statistics', 'easy', 'probability', 'A fair coin is flipped twice. What is the probability of getting heads both times?', '1/2', '1/3', '1/4', '1/8', 'C', 'P(HH) = 1/2 × 1/2 = 1/4.'),
('Data & Statistics', 'easy', 'probability', 'A standard die is rolled. What is the probability of rolling an even number?', '1/6', '1/3', '1/2', '2/3', 'C', 'Even numbers: 2, 4, 6. That''s 3 out of 6 outcomes = 1/2.'),
('Data & Statistics', 'medium', 'probability', 'A class has 12 boys and 18 girls. If a student is chosen at random, what is the probability the student is a girl?', '2/5', '3/5', '1/2', '2/3', 'B', 'P(girl) = 18/(12+18) = 18/30 = 3/5.'),
('Data & Statistics', 'medium', 'probability', 'Two events are independent. P(A) = 0.4 and P(B) = 0.3. What is P(A and B)?', '0.7', '0.12', '0.1', '0.35', 'B', 'For independent events, P(A and B) = P(A) × P(B) = 0.4 × 0.3 = 0.12.'),
('Data & Statistics', 'hard', 'probability', 'A survey shows 60% of students play sports and 40% play an instrument. 20% do both. What is the probability a student does at least one?', '60%', '80%', '100%', '70%', 'B', 'P(A or B) = P(A) + P(B) - P(A and B) = 60% + 40% - 20% = 80%.'),
('Data & Statistics', 'hard', 'probability', 'In a group of 100 people, 45 speak Spanish, 30 speak French, and 10 speak both. What is the probability that a randomly chosen person speaks neither language?', '25/100', '35/100', '55/100', '65/100', 'B', 'Spanish or French = 45 + 30 - 10 = 65. Neither = 100 - 65 = 35. P = 35/100.');

-- Mean Median Mode
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'easy', 'mean-median-mode', 'What is the mean of 4, 6, 8, 10, 12?', '7', '8', '9', '10', 'B', 'Mean = (4+6+8+10+12)/5 = 40/5 = 8.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'What is the median of 3, 7, 1, 9, 5?', '3', '5', '7', '9', 'B', 'Ordered: 1, 3, 5, 7, 9. The middle value is 5.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'What is the mode of 2, 3, 3, 5, 7, 3, 8?', '2', '3', '5', '7', 'B', 'Mode is the most frequent value. 3 appears three times.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'A student has test scores of 85, 90, 78, and 92. What score does she need on the 5th test to have a mean of 88?', '95', '92', '88', '85', 'A', 'Need total = 88 × 5 = 440. Current total = 85+90+78+92 = 345. Need 440-345 = 95.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'The dataset {2, 5, 7, 8, 12, 15, 42} has a mean of 13 and median of 8. Which measure better represents the typical value?', 'Mean', 'Median', 'Mode', 'Range', 'B', 'The outlier (42) pulls the mean up. The median (8) better represents the typical value in this skewed dataset.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'Removing which value from {3, 5, 5, 7, 9, 11, 50} would decrease the mean the most without changing the median?', '3', '50', '11', '9', 'B', 'The median is 7 regardless. Removing 50 (the largest value) decreases the mean the most: from 90/7≈12.9 to 40/6≈6.7.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'A dataset of 10 values has a mean of 20. When an 11th value is added, the mean becomes 22. What is the 11th value?', '22', '32', '42', '44', 'C', 'Original sum = 200. New sum = 22 × 11 = 242. New value = 242 - 200 = 42.');

-- Scatterplots
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'easy', 'scatterplots', 'A scatterplot shows that as study hours increase, test scores increase. This is an example of:', 'Negative correlation', 'Positive correlation', 'No correlation', 'Causation', 'B', 'When both variables increase together, the correlation is positive.'),
('Data & Statistics', 'easy', 'scatterplots', 'A scatterplot shows points scattered randomly with no pattern. What type of correlation does this show?', 'Positive', 'Negative', 'No correlation', 'Perfect correlation', 'C', 'Random scatter with no pattern indicates no correlation between the variables.'),
('Data & Statistics', 'medium', 'scatterplots', 'A line of best fit has the equation y = 2.5x + 10. What does the slope represent?', 'For each 1-unit increase in x, y increases by 10', 'For each 1-unit increase in x, y increases by 2.5', 'The starting value of y is 2.5', 'The correlation coefficient is 2.5', 'B', 'The slope (2.5) represents the rate of change — for each 1-unit increase in x, y increases by 2.5.'),
('Data & Statistics', 'medium', 'scatterplots', 'A scatterplot of temperature vs. ice cream sales shows r = 0.92. This means:', 'Temperature causes ice cream sales', 'There is a strong positive linear relationship', 'There is a weak relationship', 'Ice cream sales cause temperature increases', 'B', 'r = 0.92 indicates a strong positive linear relationship. Correlation does not imply causation.'),
('Data & Statistics', 'hard', 'scatterplots', 'A scatterplot shows a clear curved (U-shaped) pattern, but the correlation coefficient r = 0.05. Why is r so low?', 'There is no relationship between the variables', 'The sample size is too small', 'r only measures LINEAR relationships, not curved ones', 'The data has too many outliers', 'C', 'The correlation coefficient r measures the strength of a linear relationship. A strong nonlinear pattern can have r near 0.'),
('Data & Statistics', 'hard', 'scatterplots', 'A line of best fit is y = -0.8x + 50. Using this model, predict y when x = 30.', '24', '26', '28', '30', 'B', 'y = -0.8(30) + 50 = -24 + 50 = 26.');
