-- 009: Expand Data & Statistics question bank
-- Adds ~216 new questions across all 4 data subtopics
-- 54 per subtopic (18 easy + 18 medium + 18 hard)

-- ============================================================
-- SUBTOPIC 1: tables-and-graphs (54 questions)
-- ============================================================

-- tables-and-graphs: EASY (18)
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'easy', 'tables-and-graphs', 'A table shows the number of books read by 5 students: Ali 3, Ben 5, Cara 7, Dee 2, Eli 8. What is the total number of books read?', '23', '25', '27', '20', 'B', 'Add all values: 3 + 5 + 7 + 2 + 8 = 25.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A bar graph shows shirt sales: Monday 12, Tuesday 8, Wednesday 15, Thursday 10. On which day were the most shirts sold?', 'Monday', 'Tuesday', 'Thursday', 'Wednesday', 'D', 'Wednesday had the highest value at 15 shirts.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A table shows test scores for 4 students: 80, 90, 70, 100. What is the range of the scores?', '20', '25', '35', '30', 'D', 'Range = max - min = 100 - 70 = 30.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A pie chart shows that 40% of students prefer pizza, 30% prefer tacos, and the rest prefer burgers. What percent prefer burgers?', '20%', '25%', '30%', '35%', 'C', '100% - 40% - 30% = 30%.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A table shows miles driven each day: Mon 45, Tue 60, Wed 30, Thu 55, Fri 50. How many total miles were driven?', '230', '220', '250', '240', 'D', '45 + 60 + 30 + 55 + 50 = 240 miles.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A line graph shows temperature over 4 hours: 60°F, 65°F, 63°F, 70°F. What was the temperature increase from hour 1 to hour 4?', '8°F', '10°F', '5°F', '7°F', 'B', '70 - 60 = 10°F increase.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A table shows goals scored by a soccer team in 6 games: 2, 0, 3, 1, 4, 2. In how many games did the team score 2 or more goals?', '3', '4', '5', '2', 'B', 'Games with 2+ goals: 2, 3, 4, 2 — that is 4 games.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A two-way table shows 30 boys and 20 girls in a class. Of the boys, 18 play sports. What fraction of the boys play sports?', '3/5', '2/5', '9/10', '1/2', 'A', '18/30 = 3/5.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A histogram shows the following frequency of quiz scores: 60-69 has 3 students, 70-79 has 8, 80-89 has 12, 90-100 has 7. How many students took the quiz?', '28', '30', '32', '25', 'B', '3 + 8 + 12 + 7 = 30 students.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A table shows the number of pets owned: 0 pets (5 families), 1 pet (8 families), 2 pets (4 families), 3 pets (3 families). How many families were surveyed?', '18', '20', '22', '16', 'B', '5 + 8 + 4 + 3 = 20 families.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A bar graph shows rainfall in inches: Jan 2.5, Feb 3.0, Mar 4.5, Apr 5.0. What is the difference in rainfall between April and January?', '2.0', '2.5', '3.0', '1.5', 'B', '5.0 - 2.5 = 2.5 inches.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A table shows the favorite colors of 40 students: Red 12, Blue 15, Green 8, Yellow 5. What percentage chose Blue?', '30%', '37.5%', '40%', '25%', 'B', '15/40 = 0.375 = 37.5%.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A table shows hours studied and test scores for 4 students: (1, 65), (2, 75), (3, 80), (4, 90). As hours increase, what happens to scores?', 'They increase', 'They decrease', 'They stay the same', 'No pattern', 'A', 'Scores increase as hours increase, showing a positive relationship.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A frequency table shows ages at a camp: age 10 (6 kids), age 11 (9 kids), age 12 (5 kids). What is the most common age?', '10', 'Cannot determine', '12', '11', 'D', 'Age 11 has the highest frequency at 9 kids.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A line graph shows the price of a stock over 5 days: $10, $12, $9, $14, $13. Between which consecutive days did the stock price decrease the most?', 'Day 1 to Day 2', 'Day 2 to Day 3', 'Day 3 to Day 4', 'Day 4 to Day 5', 'B', 'Day 2 to Day 3 dropped from $12 to $9 = $3 decrease, which is the largest drop.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A table shows the number of cars in a parking lot each hour: 8 AM (20), 9 AM (35), 10 AM (50), 11 AM (45). At what time were the most cars present?', '8 AM', '9 AM', '10 AM', '11 AM', 'C', '10 AM had the most cars at 50.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A circle graph shows how a student spends 24 hours: Sleep 8 hrs, School 7 hrs, Homework 3 hrs, Other 6 hrs. What fraction of the day is spent on school?', '7/24', '1/3', '7/12', '1/4', 'A', '7 hours out of 24 = 7/24.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A table shows weekly earnings: Week 1 $200, Week 2 $250, Week 3 $225, Week 4 $275. What is the total earned over 4 weeks?', '$900', '$925', '$950', '$975', 'C', '200 + 250 + 225 + 275 = 950.');

-- tables-and-graphs: MEDIUM (18)
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'medium', 'tables-and-graphs', 'A table shows sales data for two stores over 3 months. Store A: 120, 150, 180. Store B: 200, 160, 140. In which month did Store A first outsell Store B?', 'Month 1', 'Month 2', 'Month 3', 'Store A never outsells Store B', 'C', 'Month 3: Store A (180) > Store B (140). In months 1 and 2, Store B was higher.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A two-way table shows 60 students: 35 take math, 25 take science. Of the math students, 20 are juniors. Of the science students, 10 are juniors. What fraction of all juniors take math?', '2/3', '4/7', '20/35', '20/60', 'A', 'Total juniors = 20 + 10 = 30. Fraction taking math = 20/30 = 2/3.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A bar graph shows quarterly profits: Q1 $50K, Q2 $65K, Q3 $80K, Q4 $55K. What is the percent increase from Q1 to Q3?', '50%', '60%', '30%', '40%', 'B', 'Increase = 80 - 50 = 30. Percent increase = 30/50 = 0.60 = 60%.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A table shows the number of applicants and accepted students at 4 colleges. College X: 500 applied, 150 accepted. What is College X''s acceptance rate?', '25%', '30%', '33%', '35%', 'B', '150/500 = 0.30 = 30%.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A grouped frequency table shows test scores: 50-59 (4), 60-69 (7), 70-79 (12), 80-89 (15), 90-99 (6). What percentage of students scored 80 or above?', '44.7%', '47.7%', '50.0%', '52.3%', 'B', 'Students 80+: 15 + 6 = 21. Total: 4 + 7 + 12 + 15 + 6 = 44. Percentage: 21/44 ≈ 47.7%.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A line graph shows population growth: Year 0 (1000), Year 5 (1500), Year 10 (2250). If the pattern continues at the same rate, what is the approximate population at Year 15?', '2750', '3000', '3500', '3375', 'D', 'The population grows by a factor of 1.5 every 5 years: 2250 × 1.5 = 3375.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A table shows survey results: 45 people prefer brand A, 30 prefer brand B, and 25 prefer brand C. A new survey of 400 people from the same population is conducted. How many would you expect to prefer brand A?', '150', '160', '170', '180', 'D', 'Total original = 100. Brand A proportion = 45/100 = 0.45. Expected = 0.45 × 400 = 180.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A stacked bar graph shows total sales of 200 items: 80 electronics, 60 clothing, and the rest are books. Books made up what percent of total sales?', '25%', '30%', '35%', '40%', 'B', 'Books = 200 - 80 - 60 = 60. Percentage = 60/200 = 30%.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A two-way table: Of 120 surveyed adults, 50 exercise regularly and eat healthy, 20 exercise but don''t eat healthy, 15 don''t exercise but eat healthy, and 35 do neither. What percent of those who exercise also eat healthy?', '50%', '62.5%', '71.4%', '76.9%', 'C', 'Total who exercise = 50 + 20 = 70. Of those, 50 eat healthy. 50/70 ≈ 71.4%.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A table shows monthly expenses: Rent $1200, Food $400, Transport $300, Utilities $200, Other $400. If income is $3000, what percent of income is saved?', '10%', '12.5%', '16.7%', '20%', 'C', 'Total expenses = 1200 + 400 + 300 + 200 + 400 = 2500. Saved = 3000 - 2500 = 500. Percent = 500/3000 ≈ 16.7%.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A double bar graph compares boys and girls in 3 activities. Sports: 40 boys, 25 girls. Music: 15 boys, 30 girls. Art: 20 boys, 20 girls. What is the ratio of boys to girls across all activities?', '3:4', '5:4', '1:1', '4:5', 'C', 'Total boys = 40 + 15 + 20 = 75. Total girls = 25 + 30 + 20 = 75. Ratio = 75:75 = 1:1.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A table shows plant growth in cm over 6 weeks: 2, 5, 9, 14, 20, 27. What is the average weekly growth?', '4.0 cm', '4.5 cm', '5.4 cm', '5.0 cm', 'D', 'Total growth = 27 - 2 = 25 cm over 5 intervals (week 1 to 6). Average weekly growth = 25/5 = 5.0 cm per week.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A relative frequency table shows that 0.35 of customers buy product X, 0.25 buy product Y, and the rest buy product Z. Out of 500 customers, how many buy product Z?', '175', '200', '225', '250', 'B', 'Proportion for Z = 1 - 0.35 - 0.25 = 0.40. Number = 0.40 × 500 = 200.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A table shows employee counts by department: Sales 45, Engineering 60, Marketing 30, HR 15. The company plans to hire 20% more in each department. How many total employees will there be?', '162', '170', '190', '180', 'D', 'Current total = 45 + 60 + 30 + 15 = 150. After 20% increase: 150 × 1.20 = 180.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A histogram shows commute times: 0-10 min (5), 10-20 min (12), 20-30 min (18), 30-40 min (10), 40-50 min (5). What percent of commuters have a commute under 20 minutes?', '34%', '30%', '38%', '40%', 'A', 'Under 20 min: 5 + 12 = 17. Total = 5 + 12 + 18 + 10 + 5 = 50. Percent = 17/50 = 34%.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A table shows that in 2020, a city had 250,000 residents and in 2023 it had 280,000. What is the average annual increase?', '8,000', '9,000', '10,000', '11,000', 'C', 'Increase = 280,000 - 250,000 = 30,000 over 3 years. Average annual = 30,000/3 = 10,000.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A two-way table shows 200 students: 90 are female. Of males, 60% participate in clubs. Of females, 70% participate in clubs. How many students total participate in clubs?', '119', '125', '129', '135', 'C', 'Males = 200 - 90 = 110. Male club members = 0.60 × 110 = 66. Female club members = 0.70 × 90 = 63. Total = 66 + 63 = 129.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A line graph shows monthly website visits (in thousands): Jan 10, Feb 12, Mar 15, Apr 18, May 22, Jun 20. What is the percent decrease from May to June?', '8.3%', '9.1%', '10%', '11.1%', 'B', 'Decrease = 22 - 20 = 2. Percent decrease = 2/22 ≈ 9.1%.');

-- tables-and-graphs: HARD (18)
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'hard', 'tables-and-graphs', 'A two-way table shows 300 survey respondents by age group (Under 30, 30+) and opinion (Favor, Oppose). Under 30: 90 Favor, 60 Oppose. 30+: 70 Favor, 80 Oppose. What is the relative risk of favoring the proposal for Under 30 vs 30+?', '1.20', '1.29', '1.35', '1.50', 'B', 'Under 30 favor rate = 90/150 = 0.60. 30+ favor rate = 70/150 ≈ 0.467. Relative risk = 0.60/0.467 ≈ 1.29.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A table shows revenue and costs for 4 products. Product A: Revenue $5000, Cost $3500. Product B: $8000, $5200. Product C: $3000, $2400. Product D: $6000, $4800. Which product has the highest profit margin (profit/revenue)?', 'A', 'B', 'C', 'D', 'B', 'Margins: A = 1500/5000 = 30%, B = 2800/8000 = 35%, C = 600/3000 = 20%, D = 1200/6000 = 20%. B is highest at 35%.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A cumulative frequency table shows exam scores: up to 60 (8 students), up to 70 (23 students), up to 80 (48 students), up to 90 (72 students), up to 100 (80 students). Approximately what score is the 60th percentile?', '75', '72', '78', '80', 'A', '60th percentile = 0.60 × 80 = 48th student. The 48th student falls at the boundary of "up to 80," meaning roughly 75 by interpolation within the 70-80 range.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A table shows data from two groups in an experiment. Group A (n=50): mean score 78, std dev 6. Group B (n=50): mean score 82, std dev 8. Which statement is best supported?', 'Group B performed better and more consistently', 'The groups performed equally', 'Group A performed better and more consistently', 'Group B performed better but less consistently', 'D', 'Group B has a higher mean (82 > 78) but a larger standard deviation (8 > 6), meaning more variability and less consistency.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A segmented bar graph shows market share for 3 companies over 2 years. In Year 1, Company X has 40%, Y has 35%, Z has 25%. In Year 2, the total market grew by 20% and X''s share dropped to 35%. If the total Year 1 market was $1M, what is X''s Year 2 revenue?', '$350,000', '$400,000', '$420,000', '$480,000', 'C', 'Year 2 total = $1M × 1.20 = $1.2M. X''s share = 35% of $1.2M = $420,000.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A frequency distribution shows ages of 100 marathon runners: 20-29 (15), 30-39 (28), 40-49 (32), 50-59 (18), 60-69 (7). Using midpoints, estimate the mean age.', '39.9', '40.9', '41.9', '42.9', 'C', 'Using midpoints: 15(24.5) + 28(34.5) + 32(44.5) + 18(54.5) + 7(64.5) = 367.5 + 966 + 1424 + 981 + 451.5 = 4190. Mean = 4190/100 = 41.9.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A table shows quarterly sales and the year-over-year percent change: Q1 +5%, Q2 +8%, Q3 -3%, Q4 +10%. If Q1 of last year had sales of $200,000, what are Q1 sales this year?', '$208,000', '$210,000', '$216,000', '$220,000', 'B', 'Q1 this year = $200,000 × 1.05 = $210,000.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A two-way table shows 400 patients: 180 received Drug A, 220 received Drug B. Of Drug A patients, 135 improved. Of Drug B patients, 154 improved. What is the difference in improvement rates?', '3%', '5%', '7%', '10%', 'B', 'Drug A rate = 135/180 = 75%. Drug B rate = 154/220 = 70%. Difference = 75% - 70% = 5%.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A table shows test results across 3 schools. School A: 120 students, avg 72. School B: 80 students, avg 85. School C: 100 students, avg 78. What is the overall weighted average?', '77.0', '77.5', '78.0', '78.3', 'B', 'Weighted avg = (120×72 + 80×85 + 100×78)/300 = (8640 + 6800 + 7800)/300 = 23240/300 ≈ 77.5.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A graph shows exponential growth of bacteria: 100 at hour 0, 200 at hour 1, 400 at hour 2. The growth is modeled by N = 100(2^t). At what time will the population reach 6400?', 't = 5', 't = 6', 't = 7', 't = 8', 'B', '6400 = 100(2^t), so 2^t = 64, meaning t = 6.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A table shows income data for two cities. City A median: $52,000, mean: $68,000. City B median: $55,000, mean: $57,000. Which city likely has more income inequality?', 'City A', 'City B', 'They are equal', 'Cannot be determined', 'A', 'City A has a large gap between mean and median ($16K), suggesting a right skew caused by high earners pulling up the mean. City B''s mean and median are close, indicating less inequality.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A contingency table shows 500 voters: 200 Democrats (140 favor policy), 180 Republicans (54 favor), 120 Independents (72 favor). What percent of all who favor the policy are Democrats?', '48.6%', '50.0%', '52.6%', '55.0%', 'C', 'Total favor = 140 + 54 + 72 = 266. Democrats who favor = 140. Percent = 140/266 ≈ 52.6%.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A table shows that Company X''s revenue was $2M in 2020 and grew 15% annually. Company Y''s was $3M in 2020 and grew 5% annually. In which year does X first exceed Y?', '2025', '2026', '2027', '2028', 'A', 'X = 2(1.15)^t, Y = 3(1.05)^t. At t=4: X=3.50M, Y=3.65M (Y>X). At t=5: X=4.02M, Y=3.83M (X>Y). So X first exceeds Y in 2025.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A table shows the results of a survey of 1000 people about exercise frequency: Daily (120), Several times/week (280), Once/week (250), Rarely (200), Never (150). A researcher claims that over half the respondents exercise at least once a week. Is this claim supported?', 'Yes, 65% exercise at least once a week', 'Yes, 53% exercise at least once a week', 'No, only 40% exercise at least once a week', 'No, only 48% exercise at least once a week', 'A', 'At least once/week: 120 + 280 + 250 = 650 out of 1000 = 65%. The claim is supported.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A table compares pass rates on a certification exam before and after a new training program. Before: 200 tested, 120 passed. After: 250 tested, 175 passed. What is the absolute increase in the pass rate?', '8%', '10%', '12%', '15%', 'B', 'Before: 120/200 = 60%. After: 175/250 = 70%. Increase = 70% - 60% = 10%.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A dot plot shows the distribution of household sizes: 1 person (4 dots), 2 (9 dots), 3 (11 dots), 4 (8 dots), 5 (5 dots), 6 (3 dots). If one household of size 6 is removed and replaced by one of size 1, how does the median change?', 'Decreases by 1', 'Decreases by 0.5', 'Increases by 0.5', 'Stays the same', 'D', 'Total = 40 households. Median is average of 20th and 21st values. Cumulative: size 1 (4), size 2 (13), size 3 (24). Both 20th and 21st values are 3. After swap: total still 40, size 1 becomes 5, cumulative at size 2 is 14, at size 3 is 25. The 20th and 21st are still 3. Median unchanged.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A table shows a company''s debt-to-equity ratio over 5 years: 2.5, 2.1, 1.8, 1.5, 1.2. The company''s equity was constant at $4M. By how much did debt decrease from Year 1 to Year 5?', '$4.2M', '$4.8M', '$5.0M', '$5.2M', 'D', 'Year 1 debt = 2.5 × $4M = $10M. Year 5 debt = 1.2 × $4M = $4.8M. Decrease = $10M - $4.8M = $5.2M.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A table shows that a standardized test has a mean of 500 and standard deviation of 100. A student scores 720. Approximately what percentile is this score if scores are normally distributed? (Use the empirical rule.)', '84th', '95th', '99th', '97.5th', 'D', '720 is 2.2 standard deviations above the mean. Using the empirical rule, about 95% fall within 2 SDs, so 2 SDs above ≈ 97.5th percentile.');

-- ============================================================
-- SUBTOPIC 2: probability (54 questions)
-- ============================================================

-- probability: EASY (18)
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'easy', 'probability', 'A bag contains 3 red, 5 blue, and 2 green marbles. What is the probability of drawing a blue marble?', '1/5', '3/10', '1/2', '2/5', 'C', 'Total marbles = 10. P(blue) = 5/10 = 1/2.'),
('Data & Statistics', 'easy', 'probability', 'A fair six-sided die is rolled. What is the probability of rolling a number greater than 4?', '1/3', '1/6', '1/2', '2/3', 'A', 'Numbers greater than 4 are 5 and 6. P = 2/6 = 1/3.'),
('Data & Statistics', 'easy', 'probability', 'A coin is flipped twice. What is the probability of getting heads both times?', '1/8', '1/4', '1/3', '1/2', 'B', 'P(HH) = 1/2 × 1/2 = 1/4.'),
('Data & Statistics', 'easy', 'probability', 'A spinner has 8 equal sections numbered 1-8. What is the probability of landing on an even number?', '3/8', '1/2', '5/8', '1/4', 'B', 'Even numbers: 2, 4, 6, 8 = 4 out of 8 = 1/2.'),
('Data & Statistics', 'easy', 'probability', 'There are 12 cards: 4 red, 4 blue, 4 green. One card is drawn at random. What is the probability it is NOT red?', '1/3', '1/2', '2/3', '3/4', 'C', 'Not red = 8 out of 12 = 2/3.'),
('Data & Statistics', 'easy', 'probability', 'A class has 15 boys and 10 girls. If a student is chosen at random, what is the probability of choosing a girl?', '2/5', '3/5', '1/3', '2/3', 'A', 'Total = 25. P(girl) = 10/25 = 2/5.'),
('Data & Statistics', 'easy', 'probability', 'A jar has 6 red and 4 white jelly beans. What is the probability of picking a red jelly bean?', '2/5', '1/2', '3/5', '2/3', 'C', 'Total = 10. P(red) = 6/10 = 3/5.'),
('Data & Statistics', 'easy', 'probability', 'A standard deck has 52 cards. What is the probability of drawing a heart?', '1/13', '1/4', '1/2', '1/52', 'B', 'There are 13 hearts in a deck of 52. P = 13/52 = 1/4.'),
('Data & Statistics', 'easy', 'probability', 'What is the probability of rolling a 3 on a fair six-sided die?', '1/2', '1/3', '1/4', '1/6', 'D', 'There is one 3 out of six faces. P = 1/6.'),
('Data & Statistics', 'easy', 'probability', 'A box has 5 apples and 3 oranges. You randomly pick one fruit. What is the probability it is an apple?', '3/8', '1/2', '3/5', '5/8', 'D', 'Total = 8. P(apple) = 5/8.'),
('Data & Statistics', 'easy', 'probability', 'Two fair coins are flipped. What is the probability of getting at least one head?', '1/4', '1/2', '3/4', '1', 'C', 'P(at least one head) = 1 - P(no heads) = 1 - 1/4 = 3/4.'),
('Data & Statistics', 'easy', 'probability', 'A bag has 10 tiles labeled 1-10. What is the probability of drawing a number less than 4?', '3/10', '1/5', '2/5', '1/2', 'A', 'Numbers less than 4: 1, 2, 3. P = 3/10.'),
('Data & Statistics', 'easy', 'probability', 'In a group of 20 students, 8 wear glasses. What is the probability that a randomly selected student wears glasses?', '1/5', '3/10', '1/2', '2/5', 'D', 'P = 8/20 = 2/5.'),
('Data & Statistics', 'easy', 'probability', 'A letter is chosen at random from the word STATISTICS. What is the probability of choosing the letter S?', '1/10', '1/5', '3/10', '2/5', 'C', 'STATISTICS has 10 letters: S, T, A, T, I, S, T, I, C, S. There are 3 S''s. P = 3/10.'),
('Data & Statistics', 'easy', 'probability', 'A die is rolled. What is the probability of rolling an odd number?', '1/6', '1/3', '2/3', '1/2', 'D', 'Odd numbers: 1, 3, 5 = 3 out of 6 = 1/2.'),
('Data & Statistics', 'easy', 'probability', 'A weather forecast says there is a 70% chance of rain. What is the probability it will NOT rain?', '20%', '30%', '40%', '50%', 'B', 'P(no rain) = 100% - 70% = 30%.'),
('Data & Statistics', 'easy', 'probability', 'A bag contains 4 red, 3 blue, and 3 yellow balls. What is the probability of drawing a red or blue ball?', '2/5', '3/10', '7/10', '1/2', 'C', 'Red or blue = 4 + 3 = 7. Total = 10. P = 7/10.'),
('Data & Statistics', 'easy', 'probability', 'A number is randomly selected from 1 to 20. What is the probability it is a multiple of 5?', '1/10', '1/4', '3/20', '1/5', 'D', 'Multiples of 5 from 1-20: 5, 10, 15, 20 = 4 numbers. P = 4/20 = 1/5.');

-- probability: MEDIUM (18)
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'medium', 'probability', 'A bag has 6 red and 4 blue marbles. Two marbles are drawn without replacement. What is the probability both are red?', '1/3', '2/5', '3/10', '1/2', 'A', 'P = (6/10)(5/9) = 30/90 = 1/3.'),
('Data & Statistics', 'medium', 'probability', 'Two fair dice are rolled. What is the probability that the sum is 7?', '1/12', '1/9', '1/6', '5/36', 'C', 'Combinations summing to 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6. P = 6/36 = 1/6.'),
('Data & Statistics', 'medium', 'probability', 'A committee of 2 is chosen from 5 men and 3 women. What is the probability both are women?', '3/28', '1/7', '3/14', '1/4', 'A', 'C(3,2)/C(8,2) = 3/28.'),
('Data & Statistics', 'medium', 'probability', 'A student guesses randomly on a 4-question true/false quiz. What is the probability of getting all 4 correct?', '1/4', '1/8', '1/16', '1/32', 'C', 'P = (1/2)^4 = 1/16.'),
('Data & Statistics', 'medium', 'probability', 'In a survey, 60% of people like chocolate and 40% like vanilla. If preferences are independent, what is the probability a random person likes both?', '24%', '20%', '30%', '40%', 'A', 'P(both) = 0.60 × 0.40 = 0.24 = 24%.'),
('Data & Statistics', 'medium', 'probability', 'A jar contains 3 red, 4 green, and 5 blue marbles. If one marble is drawn at random, what is the probability it is NOT green?', '1/3', '1/2', '3/4', '2/3', 'D', 'Not green = 3 + 5 = 8 out of 12 = 2/3.'),
('Data & Statistics', 'medium', 'probability', 'A card is drawn from a standard 52-card deck. What is the probability it is a face card (Jack, Queen, King)?', '3/52', '1/13', '3/13', '4/13', 'C', 'Face cards = 12 (3 per suit × 4 suits). P = 12/52 = 3/13.'),
('Data & Statistics', 'medium', 'probability', 'Events A and B are independent with P(A) = 0.3 and P(B) = 0.5. What is P(A or B)?', '0.60', '0.65', '0.70', '0.80', 'B', 'P(A or B) = P(A) + P(B) - P(A and B) = 0.3 + 0.5 - (0.3)(0.5) = 0.8 - 0.15 = 0.65.'),
('Data & Statistics', 'medium', 'probability', 'A box has 10 light bulbs, 3 of which are defective. If 2 bulbs are selected at random without replacement, what is the probability that at least one is defective?', '8/15', '7/15', '1/2', '14/30', 'A', 'P(at least 1 defective) = 1 - P(none defective) = 1 - (7/10)(6/9) = 1 - 42/90 = 1 - 7/15 = 8/15.'),
('Data & Statistics', 'medium', 'probability', 'A password is 3 digits long (each digit 0-9). What is the probability a randomly generated password has all different digits?', '18/25', '36/50', '72/100', 'All of the above', 'D', 'P = (10/10)(9/10)(8/10) = 720/1000 = 72/100 = 36/50 = 18/25. All three options are equivalent.'),
('Data & Statistics', 'medium', 'probability', 'A spinner is divided into 5 equal sections: 2 red, 2 blue, 1 green. If the spinner is spun twice, what is the probability of landing on red both times?', '1/25', '2/25', '4/25', '2/5', 'C', 'P(red) = 2/5. P(red twice) = (2/5)² = 4/25.'),
('Data & Statistics', 'medium', 'probability', 'In a class of 30, 18 play basketball and 12 play soccer. If 6 play both, what is the probability a randomly chosen student plays basketball or soccer?', '3/5', '4/5', '7/10', '24/30', 'B', 'By inclusion-exclusion: 18 + 12 - 6 = 24. P = 24/30 = 4/5.'),
('Data & Statistics', 'medium', 'probability', 'A test has 5 multiple-choice questions, each with 4 options. What is the probability of guessing the first two questions correctly?', '1/4', '1/8', '1/20', '1/16', 'D', 'P = (1/4)(1/4) = 1/16.'),
('Data & Statistics', 'medium', 'probability', 'A bag has 8 tiles: 3 labeled A, 2 labeled B, 3 labeled C. Two tiles are drawn without replacement. What is the probability both are labeled A?', '3/28', '1/8', '9/64', '3/56', 'A', 'P = (3/8)(2/7) = 6/56 = 3/28.'),
('Data & Statistics', 'medium', 'probability', 'A fair coin is flipped 3 times. What is the probability of getting exactly 2 heads?', '1/4', '1/8', '1/2', '3/8', 'D', 'C(3,2) × (1/2)^3 = 3 × 1/8 = 3/8.'),
('Data & Statistics', 'medium', 'probability', 'In a standard deck of 52 cards, what is the probability of drawing a red card or an ace?', '15/26', '30/52', '28/52', '7/13', 'D', 'Red cards = 26, Aces = 4, Red aces = 2. P = (26 + 4 - 2)/52 = 28/52 = 7/13.'),
('Data & Statistics', 'medium', 'probability', 'A survey found 45% of residents own a dog and 30% own a cat. If 15% own both, what percent own neither?', '30%', '35%', '40%', '45%', 'C', 'Own dog or cat = 45 + 30 - 15 = 60%. Neither = 100 - 60 = 40%.'),
('Data & Statistics', 'medium', 'probability', 'A lottery has 100 tickets. There are 5 winning tickets. If you buy 3 tickets, what is the approximate probability that at least one wins?', '14.3%', '15.0%', '14.0%', '13.5%', 'A', 'P(no win) = (95/100)(94/99)(93/98) = (95×94×93)/(100×99×98) = 830,490/970,200 ≈ 0.856. P(at least 1) ≈ 0.144 = 14.4%. Closest is 14.3%.');

-- probability: HARD (18)
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'hard', 'probability', 'A bag has 5 red and 7 blue marbles. Three marbles are drawn without replacement. What is the probability all three are blue?', '7/44', '1/6', '21/110', '35/220', 'A', 'P = (7/12)(6/11)(5/10) = 210/1320 = 7/44.'),
('Data & Statistics', 'hard', 'probability', 'Two fair dice are rolled. What is the probability that the product of the two numbers is even?', '1/4', '1/2', '3/4', '2/3', 'C', 'P(product odd) = P(both odd) = (3/6)(3/6) = 1/4. P(product even) = 1 - 1/4 = 3/4.'),
('Data & Statistics', 'hard', 'probability', 'A class has 10 students. A committee of 3 is chosen at random. What is the probability that a specific pair of students (Alice and Bob) are both on the committee?', '1/15', '2/15', '3/10', '1/10', 'A', 'If Alice and Bob are on the committee, the 3rd member is chosen from the remaining 8. Ways = C(8,1)=8. Total committees = C(10,3) = 120. P = 8/120 = 1/15.'),
('Data & Statistics', 'hard', 'probability', 'A disease affects 1% of a population. A test has 95% sensitivity and 90% specificity. If a person tests positive, what is the approximate probability they have the disease?', '8.8%', '9.6%', '12.0%', '15.5%', 'A', 'Using Bayes: P(D|+) = (0.01×0.95)/((0.01×0.95)+(0.99×0.10)) = 0.0095/(0.0095+0.099) = 0.0095/0.1085 ≈ 8.8%.'),
('Data & Statistics', 'hard', 'probability', 'Five people sit in a row. What is the probability that two specific people sit next to each other?', '1/5', '2/5', '3/10', '1/4', 'B', 'Treat the pair as one unit: 4! × 2 arrangements with them adjacent. Total = 5!. P = (4!×2)/5! = 48/120 = 2/5.'),
('Data & Statistics', 'hard', 'probability', 'A box contains 4 red, 3 blue, and 3 green balls. Two balls are drawn without replacement. What is the probability they are the same color?', '2/15', '8/30', '1/3', '4/15', 'D', 'Same color: C(4,2)+C(3,2)+C(3,2) = 6+3+3 = 12. Total = C(10,2) = 45. P = 12/45 = 4/15.'),
('Data & Statistics', 'hard', 'probability', 'In a game, you roll a fair die. You win $10 if you roll a 6, $5 if you roll a 5, and lose $3 otherwise. What is the expected value of one play?', '-$0.33', '$0.17', '$0.50', '$1.00', 'C', 'EV = (1/6)(10) + (1/6)(5) + (4/6)(-3) = 10/6 + 5/6 - 12/6 = 3/6 = $0.50.'),
('Data & Statistics', 'hard', 'probability', 'A deck has 10 cards: 4 aces, 3 kings, 3 queens. Three cards are drawn without replacement. What is the probability of getting exactly 2 aces?', '7/20', '1/4', '21/60', '3/10', 'D', 'Ways: C(4,2)×C(6,1) = 6×6 = 36. Total: C(10,3) = 120. P = 36/120 = 3/10.'),
('Data & Statistics', 'hard', 'probability', 'A fair coin is flipped 5 times. What is the probability of getting at least 4 heads?', '3/16', '5/32', '1/4', '7/32', 'A', 'P(4 heads) = C(5,4)(1/2)^5 = 5/32. P(5 heads) = 1/32. P(at least 4) = 6/32 = 3/16.'),
('Data & Statistics', 'hard', 'probability', 'A jar has 8 balls numbered 1-8. Two are drawn without replacement. What is the probability the sum is at least 13?', '1/7', '3/28', '4/28', '5/28', 'A', 'Pairs summing to ≥13: (5,8)=13, (6,7)=13, (6,8)=14, (7,8)=15. That is 4 pairs out of C(8,2)=28. P = 4/28 = 1/7.'),
('Data & Statistics', 'hard', 'probability', 'In a raffle, 200 tickets are sold. First prize is drawn, then second prize from remaining tickets. If you hold 5 tickets, what is the probability you win at least one prize?', '1/20', '49/995', '1/40', '995/39800', 'A', 'P(no prize) = (195/200)(194/199) = 37830/39800 ≈ 0.9505. P(at least one) ≈ 0.0495 ≈ 1/20.'),
('Data & Statistics', 'hard', 'probability', 'Three cards are drawn from a standard 52-card deck without replacement. What is the probability all three are the same suit?', '22/425', '11/850', '44/850', '3/51', 'A', 'P = 4 × C(13,3)/C(52,3) = 4×286/22100 = 1144/22100 = 286/5525. Simplify: 286/5525. Let me recompute: C(13,3)=286. C(52,3)=22100. P = 4×286/22100 = 1144/22100 = 572/11050 = 286/5525 = 22/425.'),
('Data & Statistics', 'hard', 'probability', 'A game show has 3 doors: behind one is a prize. You pick door 1. The host opens door 3 (no prize). Should you switch to door 2? What is the probability of winning if you switch?', '1/3', '1/2', '2/3', '3/4', 'C', 'This is the Monty Hall problem. Switching gives a 2/3 probability of winning because the host''s reveal provides information.'),
('Data & Statistics', 'hard', 'probability', 'A bag has 6 red and 6 blue marbles. You draw 4 without replacement. What is the probability of getting exactly 2 red and 2 blue?', '5/11', '5/33', '10/33', '1/3', 'A', 'P = C(6,2)×C(6,2)/C(12,4) = 15×15/495 = 225/495 = 5/11.'),
('Data & Statistics', 'hard', 'probability', 'A basketball player makes 80% of free throws. What is the probability she makes exactly 3 out of 4 free throws?', '40.96%', '38.4%', '32.0%', '25.6%', 'A', 'P = C(4,3)(0.8)^3(0.2)^1 = 4 × 0.512 × 0.2 = 0.4096 = 40.96%.'),
('Data & Statistics', 'hard', 'probability', 'Events A and B are mutually exclusive with P(A) = 0.35 and P(B) = 0.25. What is P(A-complement ∩ B-complement)?', '0.40', '0.45', '0.50', '0.60', 'A', 'P(A ∪ B) = 0.35 + 0.25 = 0.60 (mutually exclusive). P(A-complement ∩ B-complement) = P((A ∪ B)'') = 1 - 0.60 = 0.40.'),
('Data & Statistics', 'hard', 'probability', 'Ten people including you are randomly assigned to two teams of 5. What is the probability that you and a specific friend are on the same team?', '4/9', '5/9', '1/2', '2/5', 'A', 'After you are placed, there are 9 remaining spots and 4 are on your team. P(friend on your team) = 4/9.'),
('Data & Statistics', 'hard', 'probability', 'A bag has 3 red, 3 blue, and 3 green marbles. You draw 3 without replacement. What is the probability of getting one of each color?', '9/28', '3/14', '27/84', '3/28', 'A', 'Ways = 3×3×3 = 27. Total = C(9,3) = 84. P = 27/84 = 9/28.');

-- ============================================================
-- SUBTOPIC 3: mean-median-mode (54 questions)
-- ============================================================

-- mean-median-mode: EASY (18)
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'easy', 'mean-median-mode', 'What is the mean of the data set: 4, 8, 6, 10, 12?', '7', '10', '9', '8', 'D', 'Mean = (4+8+6+10+12)/5 = 40/5 = 8.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'What is the median of the data set: 3, 7, 1, 9, 5?', '3', '9', '7', '5', 'D', 'Sorted: 1, 3, 5, 7, 9. The middle value is 5.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'What is the mode of the data set: 2, 4, 4, 6, 8, 4, 10?', '2', '8', '6', '4', 'D', 'The value 4 appears 3 times, more than any other value.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'A student scored 80, 85, 90, 75, and 95 on five tests. What is the mean score?', '80', '83', '85', '87', 'C', 'Mean = (80+85+90+75+95)/5 = 425/5 = 85.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'What is the median of: 12, 15, 11, 18, 14, 20?', '13', '13.5', '14', '14.5', 'D', 'Sorted: 11, 12, 14, 15, 18, 20. Median = (14+15)/2 = 14.5.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'The ages of 4 siblings are 8, 12, 10, and 14. What is the range?', '4', '6', '8', '10', 'B', 'Range = 14 - 8 = 6.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'What is the mean of: 100, 200, 300?', '150', '300', '250', '200', 'D', 'Mean = (100+200+300)/3 = 600/3 = 200.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'A data set has values: 5, 5, 7, 8, 10. What is the mode?', '5', '7', '8', '10', 'A', '5 appears twice; all others appear once. Mode is 5.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'The weights of 5 packages in pounds are: 2, 3, 5, 7, 8. What is the median weight?', '3', '4', '5', '6', 'C', 'Sorted: 2, 3, 5, 7, 8. The middle value is 5.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'What is the mean of: 15, 20, 25, 30, 35?', '25', '20', '30', '27', 'A', 'Mean = (15+20+25+30+35)/5 = 125/5 = 25.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'A data set has values: 3, 3, 5, 5, 7. How many modes does it have?', '0', '1', '2', '3', 'C', 'Both 3 and 5 appear twice. The data set is bimodal with 2 modes.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'Seven friends have heights (in inches): 60, 62, 64, 65, 66, 68, 70. What is the median height?', '64', '65', '66', '67', 'B', 'The middle (4th) value of the sorted data is 65.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'The daily high temperatures for a week are: 72, 75, 78, 74, 80, 76, 73. What is the mean temperature?', '74', '75', '75.4', '76', 'C', 'Mean = (72+75+78+74+80+76+73)/7 = 528/7 ≈ 75.4.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'What is the median of: 1, 2, 3, 4?', '2', '2.5', '3', '3.5', 'B', 'Median = (2+3)/2 = 2.5.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'A student needs a mean of 90 across 4 tests. Her first 3 scores are 88, 92, and 85. What must she score on the 4th test?', '90', '93', '97', '95', 'D', 'Need total = 90 × 4 = 360. Current sum = 88+92+85 = 265. Need 360-265 = 95.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'The data set is: 10, 20, 30, 40, 50. If each value is increased by 5, what is the new mean?', '25', '30', '35', '40', 'C', 'Original mean = 30. Adding 5 to each value increases the mean by 5: new mean = 35.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'What is the range of: 14, 22, 8, 31, 17?', '17', '20', '23', '26', 'C', 'Range = 31 - 8 = 23.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'A bakery sold the following number of cakes each day: 12, 15, 12, 18, 12, 20, 16. What is the mode?', '12', '15', '16', '18', 'A', '12 appears 3 times, more than any other value.');

-- mean-median-mode: MEDIUM (18)
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'medium', 'mean-median-mode', 'A data set of 10 values has a mean of 50. If the value 30 is removed, what is the new mean?', '52.2', '53.3', '54.4', '55.5', 'A', 'Total = 50×10 = 500. Remove 30: new total = 470, new count = 9. Mean = 470/9 ≈ 52.2.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'A class of 20 students has a mean score of 78. A new student joins with a score of 99. What is the new class mean?', '78.5', '79.0', '79.5', '80.0', 'B', 'Total = 78×20 = 1560. New total = 1560+99 = 1659. New mean = 1659/21 = 79.0.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'The median of five numbers is 15. Four of the numbers are 8, 12, 20, and 25. What is the fifth number?', '13', '14', '15', '16', 'C', 'Sorted with unknown x: we need the 3rd value to be 15. If x=15, sorted: 8,12,15,20,25. Median=15. Correct.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'Data set A: {2, 4, 6, 8, 10}. Data set B: {4, 5, 6, 7, 8}. Which set has the greater standard deviation?', 'Set A', 'Set B', 'They are equal', 'Cannot be determined', 'A', 'Set A is more spread out (range 8) than Set B (range 4), so Set A has a greater standard deviation.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'The mean of 6 numbers is 12. Five of the numbers are 8, 10, 14, 16, and 11. What is the sixth number?', '9', '10', '15', '13', 'D', 'Total = 12×6 = 72. Sum of 5 = 8+10+14+16+11 = 59. Sixth = 72-59 = 13.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'A data set has values: 3, 5, 7, 9, 11, 13. If each value is doubled, what happens to the mean and median?', 'Both double', 'Mean doubles, median stays same', 'Median doubles, mean stays same', 'Neither changes', 'A', 'Doubling every value doubles both the mean and the median.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'The scores on a test are: 70, 75, 75, 80, 85, 85, 85, 90. What is the difference between the mode and the mean?', '3.125', '4.375', '5.0', '5.625', 'B', 'Mean = (70+75+75+80+85+85+85+90)/8 = 645/8 = 80.625. Mode = 85. Difference = 85 - 80.625 = 4.375.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'A set of 8 values has a mean of 25 and a median of 23. If the largest value (40) is replaced by 50, how does the mean change?', 'Increases by 1.00', 'Increases by 1.25', 'Increases by 1.50', 'Increases by 2.00', 'B', 'New total = old total + (50-40) = 200+10 = 210. New mean = 210/8 = 26.25. Change = 26.25-25 = 1.25.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'In a data set of 11 values arranged in order, the median is 45. If a new value of 50 is added, what can you say about the new median?', 'It is 45', 'It is between 45 and 50', 'It is 47.5', 'It could be 45 or higher', 'D', 'With 12 values, the median is the average of the 6th and 7th values. The new median is at least 45 but depends on where other values fall.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'The mean of a data set is 60 and the standard deviation is 5. What value is 2 standard deviations below the mean?', '45', '65', '55', '50', 'D', '60 - 2(5) = 60 - 10 = 50.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'A teacher curves test scores by adding 8 points to every score. How does this affect the mean and standard deviation?', 'Mean increases by 8, SD unchanged', 'Mean increases by 8, SD increases by 8', 'Both unchanged', 'Mean unchanged, SD increases by 8', 'A', 'Adding a constant shifts the mean by that amount but does not change the spread (standard deviation).'),
('Data & Statistics', 'medium', 'mean-median-mode', 'Group A has 15 members with mean age 30. Group B has 25 members with mean age 40. What is the combined mean age?', '34.0', '36.25', '35.0', '37.5', 'B', 'Combined mean = (15×30 + 25×40)/(15+25) = (450+1000)/40 = 1450/40 = 36.25.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'A data set has values: 10, 15, 20, 25, 30. If 10 is removed, by how much does the mean increase?', '2.0', '2.5', '3.0', '3.5', 'B', 'Original mean = 100/5 = 20. New mean = 90/4 = 22.5. Increase = 2.5.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'The median of 9 consecutive integers is 14. What is the largest integer?', '16', '17', '19', '18', 'D', 'If the median (5th value) is 14, the integers are 10, 11, 12, 13, 14, 15, 16, 17, 18. Largest is 18.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'A data set has 5 values with mean 40 and median 38. Which value, if added, would increase the median the most?', '35', '39', '42', '50', 'C', 'Current sorted set has median (3rd value) = 38. Adding 42 creates a 6-value set where the median shifts upward most, as it places a value above the current median, pulling the average of the 3rd and 4th values higher.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'The mean salary of 50 employees is $45,000. The CEO earns $500,000. What is the mean salary including the CEO?', '$53,922', '$54,000', '$53,529', '$53,824', 'A', 'Total = 50×45000 = 2,250,000. Add CEO: 2,750,000. Mean = 2,750,000/51 ≈ $53,922.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'The interquartile range (IQR) of a data set is 12 and Q1 is 25. What is Q3?', '31', '33', '37', '39', 'C', 'IQR = Q3 - Q1. Q3 = Q1 + IQR = 25 + 12 = 37.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'A set of test scores has a mean of 72 and a standard deviation of 8. According to the empirical rule, approximately what percentage of scores fall between 56 and 88?', '68%', '85%', '95%', '99.7%', 'C', '56 = 72-16 = 72-2(8). 88 = 72+16 = 72+2(8). Within 2 standard deviations ≈ 95%.');

-- mean-median-mode: HARD (18)
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'hard', 'mean-median-mode', 'The mean of a set of 20 numbers is 15. If the two largest numbers (each equal to 35) are removed, what is the new mean?', '12.5', '13.33', '13.0', '12.78', 'D', 'Total = 20×15 = 300. Remove two 35s: 300-70 = 230. New mean = 230/18 ≈ 12.78.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'The median of the set {a, 2a, 3a, 4a, 5a} where a > 0 is 21. What is the mean?', '14', '7', '35', '21', 'D', 'The median is the 3rd value: 3a = 21, so a = 7. Mean = (a+2a+3a+4a+5a)/5 = 15a/5 = 3a = 21.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'A data set has mean 50 and standard deviation 10. Every value is multiplied by 3 then 5 is added. What are the new mean and standard deviation?', 'Mean 155, SD 30', 'Mean 155, SD 35', 'Mean 150, SD 30', 'Mean 150, SD 35', 'A', 'New mean = 3(50)+5 = 155. New SD = 3(10) = 30 (adding a constant doesn''t change SD).'),
('Data & Statistics', 'hard', 'mean-median-mode', 'A sample of 100 values has mean 80 and standard deviation 12. At least what percentage of values fall between 56 and 104?', '75%', '84%', '89%', '93.75%', 'A', 'By Chebyshev''s theorem: 56 = 80-24 = 80-2(12), 104 = 80+24 = 80+2(12). At least 1-1/4 = 75% of values fall within 2 SDs.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'Two classes take the same test. Class A (n=30) has mean 75 and SD 8. Class B (n=20) has mean 85 and SD 6. What is the combined mean?', '78', '79', '80', '81', 'B', 'Combined mean = (30×75 + 20×85)/50 = (2250+1700)/50 = 3950/50 = 79.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'A data set has 7 values with a mean of 12 and a median of 10. If every value below the median is increased by 4 and every value above is decreased by 2, what is the new mean?', '11.14', '12.00', '12.86', '13.14', 'C', 'There are 3 values below the median, 1 at the median (unchanged), and 3 above. Total change = 3(4) + 3(-2) = 12 - 6 = 6. New total = 84 + 6 = 90. New mean = 90/7 ≈ 12.86.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'The mean of 5 positive integers is 15. The median is 14 and the mode is 14. What is the maximum possible value in the set?', '25', '28', '30', '33', 'D', 'Total = 75. Mode 14 appears at least twice. Median (3rd value) = 14. So two values are 14. To maximize the largest, minimize others: {1, 14, 14, 13, ...} but 3rd value must be 14 when sorted. Try: {a, b, 14, 14, e} sorted. Need mode=14, so 14 appears most. Min a and b: a=1, b=1 but then 1 appears twice too. Use a=1, b=13: {1, 13, 14, 14, e}. e = 75-1-13-14-14 = 33.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'A box plot shows Q1=20, median=30, Q3=45. A value is considered an outlier if it is more than 1.5×IQR above Q3 or below Q1. What is the upper boundary for outliers?', '72.5', '75.0', '82.5', '85.0', 'C', 'IQR = 45-20 = 25. Upper fence = Q3 + 1.5×IQR = 45 + 37.5 = 82.5.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'The mean of n numbers is 24. When 48 is added to the set, the new mean is 25. What is n?', '20', '28', '25', '23', 'D', 'Original total = 24n. New: (24n+48)/(n+1) = 25. 24n+48 = 25n+25. n = 23.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'Data set X has mean 40 and variance 16. Data set Y is created by the transformation Y = 2X - 10. What is the variance of Y?', '22', '32', '54', '64', 'D', 'Var(Y) = Var(2X-10) = 4×Var(X) = 4×16 = 64.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'A professor drops the lowest of 5 test scores. A student''s scores are 65, 75, 82, 88, 95. By how much does dropping the lowest score change the mean?', '4.0', '3.0', '5.0', '6.0', 'A', 'Original mean = (65+75+82+88+95)/5 = 405/5 = 81. New mean = (75+82+88+95)/4 = 340/4 = 85. Change = 85-81 = 4.0.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'The mean of 8 values is 20. When a 9th value is added, the mean becomes 22. What is the 9th value?', '30', '34', '36', '38', 'D', 'Original total = 8 × 20 = 160. New total = 9 × 22 = 198. The 9th value = 198 - 160 = 38.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'In a normally distributed data set with mean 100 and standard deviation 15, what score corresponds to the 84th percentile? (Use the empirical rule.)', '105', '110', '115', '120', 'C', 'The 84th percentile is approximately 1 standard deviation above the mean: 100 + 15 = 115.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'A trimmed mean removes the top and bottom 10% of values. A data set of 50 values sorted has the 5 smallest summing to 15 and the 5 largest summing to 275. The total sum is 2500. What is the 10% trimmed mean?', '52.25', '58.75', '56.50', '55.25', 'D', 'Remove 5 smallest and 5 largest: new sum = 2500-15-275 = 2210. New count = 40. Trimmed mean = 2210/40 = 55.25.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'A weighted average is calculated: Homework (20%) = 90, Midterm (30%) = 78, Final (50%) = 84. What is the weighted average?', '82.8', '83.4', '84.0', '84.6', 'B', 'Weighted avg = 0.20(90) + 0.30(78) + 0.50(84) = 18 + 23.4 + 42 = 83.4.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'The coefficient of variation (CV) of data set A is 25% and of data set B is 15%. Which data set has more relative variability?', 'A', 'B', 'They are equal', 'Cannot determine', 'A', 'CV measures relative variability. A higher CV (25% > 15%) means data set A has more relative variability.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'A data set of 15 values has Q1 = 20 and Q3 = 44. A new value of 100 is added. Is 100 an outlier by the 1.5×IQR rule?', 'Yes, it exceeds the upper fence of 80', 'Yes, it exceeds the upper fence of 80.5', 'No, the upper fence is 100', 'No, the upper fence is 108', 'A', 'IQR = 44-20 = 24. Upper fence = 44 + 1.5(24) = 44 + 36 = 80. Since 100 > 80, it is an outlier.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'The harmonic mean of two numbers a and b is 2ab/(a+b). What is the harmonic mean of 4 and 12?', '5', '6', '7', '8', 'B', 'HM = 2(4)(12)/(4+12) = 96/16 = 6.');

-- ============================================================
-- SUBTOPIC 4: scatterplots (54 questions)
-- ============================================================

-- scatterplots: EASY (18)
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'easy', 'scatterplots', 'A scatterplot shows that as study hours increase, test scores increase. What type of correlation is this?', 'Positive', 'Negative', 'No correlation', 'Exponential', 'A', 'When both variables increase together, it is a positive correlation.'),
('Data & Statistics', 'easy', 'scatterplots', 'A scatterplot of car age (years) vs. value ($) shows points trending downward from left to right. What type of association does this suggest?', 'Negative linear', 'Positive linear', 'No association', 'Positive nonlinear', 'A', 'As car age increases and value decreases, the association is negative linear.'),
('Data & Statistics', 'easy', 'scatterplots', 'A line of best fit has equation y = 2x + 10. What is the predicted y-value when x = 5?', '15', '18', '20', '25', 'C', 'y = 2(5) + 10 = 10 + 10 = 20.'),
('Data & Statistics', 'easy', 'scatterplots', 'In the equation y = 3x + 5, what does the slope (3) represent?', 'For every 1 unit increase in x, y increases by 3', 'The starting value of y', 'The average y-value', 'The maximum y-value', 'A', 'The slope represents the rate of change: y increases by 3 for each unit increase in x.'),
('Data & Statistics', 'easy', 'scatterplots', 'A scatterplot shows no clear pattern between hours of TV watched and shoe size. What is the likely correlation?', 'Strong positive', 'Strong negative', 'No correlation', 'Perfect positive', 'C', 'No clear pattern suggests no correlation between the variables.'),
('Data & Statistics', 'easy', 'scatterplots', 'A line of best fit has equation y = -4x + 100. What is the y-intercept?', '-4', '4', '96', '100', 'D', 'The y-intercept is the constant term: 100.'),
('Data & Statistics', 'easy', 'scatterplots', 'A scatterplot shows data points clustered tightly around a line. Is the correlation strong or weak?', 'Strong', 'Weak', 'No correlation', 'Cannot determine', 'A', 'Tightly clustered points around a line indicate a strong correlation.'),
('Data & Statistics', 'easy', 'scatterplots', 'A line of best fit is y = 0.5x + 20. What is the predicted y when x = 10?', '22', '23', '25', '30', 'C', 'y = 0.5(10) + 20 = 5 + 20 = 25.'),
('Data & Statistics', 'easy', 'scatterplots', 'If a correlation coefficient r = -0.85, which best describes the relationship?', 'Strong positive', 'Weak positive', 'Strong negative', 'Weak negative', 'C', 'r = -0.85 is close to -1, indicating a strong negative correlation.'),
('Data & Statistics', 'easy', 'scatterplots', 'A line of best fit for height (inches) vs. weight (pounds) is w = 4h - 100. Predict the weight of a person 65 inches tall.', '150', '155', '160', '165', 'C', 'w = 4(65) - 100 = 260 - 100 = 160 pounds.'),
('Data & Statistics', 'easy', 'scatterplots', 'In a scatterplot, what does an outlier look like?', 'A point on the line of best fit', 'A point far from the other data points', 'A point at the origin', 'A point where x = 0', 'B', 'An outlier is a data point that is far away from the general pattern of the other data.'),
('Data & Statistics', 'easy', 'scatterplots', 'A scatterplot shows temperature (°F) vs. ice cream sales ($). As temperature rises, sales rise. The line of best fit is y = 5x - 100. What are predicted sales at 80°F?', '$200', '$250', '$300', '$350', 'C', 'y = 5(80) - 100 = 400 - 100 = 300.'),
('Data & Statistics', 'easy', 'scatterplots', 'If the slope of a line of best fit is 0, what does this mean?', 'y increases as x increases', 'y decreases as x increases', 'There is no linear relationship between x and y', 'y is always 0', 'C', 'A slope of 0 means y does not change as x changes — no linear relationship.'),
('Data & Statistics', 'easy', 'scatterplots', 'A scatterplot of plant height vs. days since planting shows a positive trend. The line of best fit is y = 1.5x + 2. How tall is the plant predicted to be after 10 days?', '15 cm', '17 cm', '20 cm', '22 cm', 'B', 'y = 1.5(10) + 2 = 15 + 2 = 17 cm.'),
('Data & Statistics', 'easy', 'scatterplots', 'Which value of r indicates the strongest correlation?', 'r = 0.4', 'r = -0.3', 'r = 0.6', 'r = -0.7', 'D', 'The strength of correlation is determined by |r|. |-0.7| = 0.7 is the largest absolute value.'),
('Data & Statistics', 'easy', 'scatterplots', 'A line of best fit has equation y = -2x + 50. As x increases by 1, what happens to y?', 'y increases by 2', 'y increases by 50', 'y stays the same', 'y decreases by 2', 'D', 'The slope is -2, so y decreases by 2 for each unit increase in x.'),
('Data & Statistics', 'easy', 'scatterplots', 'A scatterplot of hours practiced vs. free-throw percentage shows an upward trend. If r = 0.92, how well does practice predict free-throw percentage?', 'Very well', 'Somewhat', 'Poorly', 'Not at all', 'A', 'r = 0.92 is close to 1, indicating a very strong positive correlation and good predictive ability.'),
('Data & Statistics', 'easy', 'scatterplots', 'A data point falls exactly on the line of best fit. What is the residual for this point?', '0', '-1', '1', 'Cannot determine', 'A', 'Residual = actual - predicted. If the point is on the line, actual = predicted, so residual = 0.');

-- scatterplots: MEDIUM (18)
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'medium', 'scatterplots', 'A line of best fit is y = 3x + 12. The actual y-value when x = 4 is 28. What is the residual?', '2', '4', '6', '8', 'B', 'Predicted = 3(4)+12 = 24. Residual = actual - predicted = 28-24 = 4.'),
('Data & Statistics', 'medium', 'scatterplots', 'A scatterplot shows the relationship between advertising spend (in $1000s) and revenue (in $1000s). The line of best fit is y = 8x + 50. If a company spends $15,000 on advertising, what is the predicted revenue?', '$150,000', '$160,000', '$180,000', '$170,000', 'D', 'x = 15 (in thousands). y = 8(15)+50 = 120+50 = 170 thousand = $170,000.'),
('Data & Statistics', 'medium', 'scatterplots', 'The correlation coefficient between two variables is r = 0.8. What is the coefficient of determination (r²)?', '0.60', '0.64', '0.72', '0.80', 'B', 'r² = (0.8)² = 0.64. This means 64% of the variation in y is explained by x.'),
('Data & Statistics', 'medium', 'scatterplots', 'A scatterplot has line of best fit y = -1.5x + 80. At what x-value does the line predict y = 0?', '40', '48', '53.3', '60', 'C', '0 = -1.5x + 80. 1.5x = 80. x = 80/1.5 ≈ 53.3.'),
('Data & Statistics', 'medium', 'scatterplots', 'Data shows: x values (1,2,3,4,5) and y values (5,8,10,14,17). Using the first and last points, what is the slope of the line connecting them?', '2.5', '3.0', '3.5', '4.0', 'B', 'Slope = (17-5)/(5-1) = 12/4 = 3.0.'),
('Data & Statistics', 'medium', 'scatterplots', 'A regression model predicts that each additional year of education increases salary by $4,500. The y-intercept is $18,000. What salary does the model predict for someone with 16 years of education?', '$86,000', '$88,000', '$90,000', '$92,000', 'C', 'y = 4500(16) + 18000 = 72000 + 18000 = $90,000.'),
('Data & Statistics', 'medium', 'scatterplots', 'A residual plot shows a clear curved pattern. What does this suggest?', 'The linear model is a good fit', 'The linear model is not appropriate', 'There is no relationship', 'The data has no outliers', 'B', 'A curved pattern in residuals indicates the relationship is not linear, so a linear model is not appropriate.'),
('Data & Statistics', 'medium', 'scatterplots', 'A scatterplot has r = -0.95. If the x-values are multiplied by -1 (reversing direction), what is the new correlation coefficient?', '-0.95', '0.90', '0', '0.95', 'D', 'Multiplying x by -1 reverses the direction of the relationship, changing the sign of r to +0.95.'),
('Data & Statistics', 'medium', 'scatterplots', 'A line of best fit is y = 2.5x + 15. Two data points are (4, 26) and (6, 32). What is the sum of their residuals?', '1', '2', '3', '4', 'C', 'At x=4: predicted = 2.5(4)+15 = 25, residual = 26-25 = 1. At x=6: predicted = 2.5(6)+15 = 30, residual = 32-30 = 2. Sum = 1+2 = 3.'),
('Data & Statistics', 'medium', 'scatterplots', 'A scatterplot of study time vs. test scores yields r² = 0.81. What percent of the variation in test scores is NOT explained by study time?', '9%', '15%', '19%', '81%', 'C', '100% - 81% = 19% is unexplained.'),
('Data & Statistics', 'medium', 'scatterplots', 'A line of best fit for age (x) vs. income in thousands (y) is y = 2x - 10. According to this model, at what age does predicted income first exceed $50,000?', '28', '29', '30', '31', 'D', '50 = 2x - 10 → 2x = 60 → x = 30. At age 30, income = exactly 50. To exceed 50, age must be greater than 30. First whole number is 31.'),
('Data & Statistics', 'medium', 'scatterplots', 'A researcher finds r = 0.65 between ice cream sales and drowning incidents. Does this prove ice cream causes drowning?', 'Yes, the correlation is strong', 'No, correlation does not imply causation', 'Yes, if r > 0.5 it proves causation', 'Not enough information', 'B', 'Correlation does not imply causation. Both variables are likely influenced by a lurking variable (temperature/summer).'),
('Data & Statistics', 'medium', 'scatterplots', 'A scatterplot of x vs. y has line of best fit y = 0.8x + 3. If a new data point (10, 14) is added, what is its residual?', '2', '3', '4', '5', 'B', 'Predicted = 0.8(10)+3 = 11. Residual = 14-11 = 3.'),
('Data & Statistics', 'medium', 'scatterplots', 'Two scatterplots show: Plot A has r = 0.55, Plot B has r = -0.78. Which plot shows a stronger linear relationship?', 'Plot A', 'Cannot determine', 'They are equal', 'Plot B', 'D', '|r| for Plot B = 0.78 > 0.55 = |r| for Plot A. Plot B has a stronger linear relationship.'),
('Data & Statistics', 'medium', 'scatterplots', 'A line of best fit for a scatterplot is y = 4x + 20. The data ranges from x = 0 to x = 10. Using this model to predict y at x = 25 is an example of what?', 'Interpolation', 'Regression', 'Correlation', 'Extrapolation', 'D', 'Using a model beyond the range of observed data is called extrapolation, which may be unreliable.'),
('Data & Statistics', 'medium', 'scatterplots', 'In a scatterplot, increasing the sample size while the relationship stays the same would typically do what to the correlation coefficient?', 'Make it closer to 0', 'Keep it about the same', 'Always make it closer to 1', 'Make it negative', 'B', 'A larger sample size gives a more reliable estimate, but the correlation coefficient stays about the same if the relationship is unchanged.'),
('Data & Statistics', 'medium', 'scatterplots', 'A scatterplot of hours worked (x) vs. earnings (y) has the equation y = 15x + 50. What does the y-intercept of 50 represent in context?', 'The hourly wage', 'Hours worked when pay is 0', 'The total earnings', 'A base pay of $50', 'D', 'The y-intercept represents earnings when hours = 0, which is a base pay or fixed component of $50.'),
('Data & Statistics', 'medium', 'scatterplots', 'A scatterplot has 20 data points. The sum of all residuals from the least-squares regression line is always what value?', '-1', '0', '1', 'Depends on the data', 'B', 'A property of least-squares regression is that the sum of residuals is always 0.');

-- scatterplots: HARD (18)
INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
('Data & Statistics', 'hard', 'scatterplots', 'A scatterplot of x vs. y yields r = 0.9. If every y-value is increased by 100, what is the new correlation coefficient?', '0.9', '0.95', '1.0', 'Cannot determine', 'A', 'Adding a constant to all y-values shifts the data but does not change the correlation coefficient. r remains 0.9.'),
('Data & Statistics', 'hard', 'scatterplots', 'A regression line is y = 1.2x + 8 with r² = 0.75. The standard deviation of y is 10. What is the standard deviation of the residuals (approximately)?', '3.5', '4.0', '7.5', '5.0', 'D', 'SD of residuals ≈ SD(y) × √(1-r²) = 10 × √(0.25) = 10 × 0.5 = 5.0.'),
('Data & Statistics', 'hard', 'scatterplots', 'Two variables have r = 0.6. A third variable is controlled for, and the partial correlation drops to r = 0.1. What does this suggest?', 'The third variable is a confounding variable', 'The original correlation was spurious', 'Both A and B', 'The variables are independent', 'C', 'When controlling for a third variable makes the correlation nearly vanish, it suggests the third variable was a confounder and the original correlation was largely spurious.'),
('Data & Statistics', 'hard', 'scatterplots', 'A scatterplot has line of best fit y = -0.6x + 45. The residuals for three points are +3, -2, and +1. What are the actual y-values if the x-values are 10, 20, and 30?', '42, 31, 28', '42, 31, 19', '42, 33, 28', '39, 33, 28', 'A', 'At x=10: predicted=39, actual=39+3=42. At x=20: predicted=33, actual=33-2=31. At x=30: predicted=27, actual=27+1=28.'),
('Data & Statistics', 'hard', 'scatterplots', 'A researcher fits both a linear model (r²=0.72) and a quadratic model (r²=0.95) to data. The linear residual plot shows a curve. Which model should be used and why?', 'Linear, because it''s simpler', 'Quadratic, because r² is higher and residuals suggest non-linearity', 'Either model works equally', 'Neither is appropriate', 'B', 'The curved residual plot indicates a linear model is inadequate. The quadratic model fits much better (r²=0.95) and addresses the non-linear pattern.'),
('Data & Statistics', 'hard', 'scatterplots', 'A regression equation is y = 2.3x + 15 with n = 50 data points. The sum of squared residuals (SSR) is 400. What is the standard error of the estimate?', '2.78', '2.89', '3.00', '8.16', 'B', 'Standard error = √(SSR/(n-2)) = √(400/48) = √8.33 ≈ 2.89.'),
('Data & Statistics', 'hard', 'scatterplots', 'In a scatterplot, an influential point is removed and the slope changes from 2.5 to 1.8. The r² changes from 0.60 to 0.85. What best describes this point?', 'It was strengthening the correlation', 'It only affected the intercept', 'It had no effect on the model', 'It was weakening the correlation and pulling the slope up', 'D', 'Removing the point decreased the slope and increased r², indicating it was an influential point that was distorting the relationship.'),
('Data & Statistics', 'hard', 'scatterplots', 'A scatterplot shows the relationship between x and y for 100 data points. The equation is y = -3x + 200 with r = -0.88. What is the predicted y when x is at the mean of x, if the mean of y is 110?', '100', '105', '115', '110', 'D', 'The regression line always passes through (mean of x, mean of y). So when x is at its mean, predicted y = mean of y = 110.'),
('Data & Statistics', 'hard', 'scatterplots', 'A line of best fit yields r² = 0.64. If a transformation (log of y) is applied and the new r² = 0.92, what is the improvement in explained variation?', '28 percentage points', '30 percentage points', '43.75%', 'Both A and C', 'A', 'The improvement is 0.92 - 0.64 = 0.28 = 28 percentage points.'),
('Data & Statistics', 'hard', 'scatterplots', 'A scatterplot has 5 points: (1,3), (2,5), (3,7), (4,9), (5,11). What is the exact equation of the line of best fit?', 'y = 2x + 1', 'y = 2x + 0.5', 'y = 2.5x', 'y = 1.5x + 2', 'A', 'All points lie perfectly on y = 2x + 1: 2(1)+1=3, 2(2)+1=5, 2(3)+1=7, 2(4)+1=9, 2(5)+1=11. Perfect fit.'),
('Data & Statistics', 'hard', 'scatterplots', 'A regression model for predicting house price (in $1000s) from square footage gives y = 0.15x + 20 with r² = 0.82. For a 2000 sq ft house, what is the predicted price and the 95% prediction interval if the standard error is $25,000?', '$320K, roughly $270K to $370K', '$320K, roughly $295K to $345K', '$350K, roughly $300K to $400K', '$300K, roughly $250K to $350K', 'A', 'Predicted = 0.15(2000)+20 = 320 ($320K). 95% interval ≈ predicted ± 2(SE) = 320 ± 50 = $270K to $370K.'),
('Data & Statistics', 'hard', 'scatterplots', 'A scatterplot of study hours (x) vs. GPA (y) has r = 0.7 for 200 students. If the data is split into freshmen (n=100, r=0.5) and upperclassmen (n=100, r=0.4), what might explain the higher overall r?', 'Simpson''s paradox', 'The groups have different means, creating a combined trend', 'Measurement error', 'Random chance', 'B', 'When subgroups have different means on both variables, combining them can create a stronger overall correlation than exists within each group—an example of aggregation effects.'),
('Data & Statistics', 'hard', 'scatterplots', 'A linear regression gives y = 5x + 30. A point has x = 8 and residual = -4. What is the actual y-value?', '62', '66', '70', '74', 'B', 'Predicted = 5(8)+30 = 70. Residual = actual - predicted. -4 = actual - 70. Actual = 66.'),
('Data & Statistics', 'hard', 'scatterplots', 'A scatterplot with 50 points has r = 0.3. Another with 500 points has r = 0.3. Which correlation is more likely to be statistically significant?', 'The one with 50 points', 'Neither is significant', 'Both are equally significant', 'The one with 500 points', 'D', 'With larger sample sizes, even moderate correlations become statistically significant because the standard error decreases.'),
('Data & Statistics', 'hard', 'scatterplots', 'An exponential model y = 50(1.1)^x fits data with r² = 0.93. What is the predicted y when x = 10?', '110.5', '120.3', '129.7', '135.0', 'C', 'y = 50(1.1)^10 = 50 × 2.5937 ≈ 129.7.'),
('Data & Statistics', 'hard', 'scatterplots', 'A scatterplot has regression line y = 0.4x + 12. The standard deviation of x is 5 and of y is 3. What is the correlation coefficient r?', '0.53', '0.60', '0.67', '0.75', 'C', 'The slope b = r × (SD_y/SD_x). So 0.4 = r × (3/5). r = 0.4 × 5/3 = 2/3 ≈ 0.67.'),
('Data & Statistics', 'hard', 'scatterplots', 'A researcher uses regression to predict y from x. The total sum of squares (SST) is 1000 and the regression sum of squares (SSR) is 720. What is the residual sum of squares (SSE)?', '180', '220', '280', '320', 'C', 'SSE = SST - SSR = 1000 - 720 = 280.'),
('Data & Statistics', 'hard', 'scatterplots', 'A scatterplot has data from two time periods. Period 1 (x=1-5) has a positive slope. Period 2 (x=6-10) has a negative slope. If a single linear model is fit to all data, the r² is likely to be:', 'Close to 1', 'Close to 0', 'Exactly 0.5', 'Negative', 'B', 'A single line cannot capture opposing trends well. The positive and negative slopes would partially cancel, resulting in a poor fit and r² close to 0.');
