-- 016: SAT Question Expansion
-- Adds 120 new questions across all 4 SAT categories
-- 30 per category (10 easy + 10 medium + 10 hard), properly subtopic-tagged

-- ===================== ALGEBRA =====================

INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
-- Algebra: Easy (10)
('Algebra', 'easy', 'linear-equations', 'A gym membership costs $15 per month plus a one-time signup fee of $40. Which equation gives the total cost C after m months?', 'C = 40m + 15', 'C = 15m + 40', 'C = 55m', 'C = 15 + 40m', 'B', 'The variable cost is $15 per month (15m) and the fixed cost is $40: C = 15m + 40.'),
('Algebra', 'easy', 'linear-equations', 'If 5x − 3 = 2x + 9, what is x?', '2', '3', '4', '6', 'C', 'Subtract 2x: 3x − 3 = 9. Add 3: 3x = 12. Divide: x = 4.'),
('Algebra', 'easy', 'systems-of-equations', 'At a bakery, 2 muffins and 1 coffee cost $7. One muffin and 1 coffee cost $4.50. What is the cost of one muffin?', '$1.50', '$2.00', '$2.50', '$3.00', 'C', 'Subtract the equations: 2m + c − (m + c) = 7 − 4.50, so m = $2.50.'),
('Algebra', 'easy', 'quadratics', 'What are the solutions to x² − 16 = 0?', 'x = 4 only', 'x = −4 only', 'x = 4 or x = −4', 'x = 8 or x = −8', 'C', 'x² = 16, so x = ±4.'),
('Algebra', 'easy', 'functions', 'If f(x) = 3x − 1, what is f(0)?', '−1', '0', '1', '3', 'A', 'f(0) = 3(0) − 1 = −1.'),
('Algebra', 'easy', 'inequalities', 'Which value of x satisfies 3x + 1 > 16?', '3', '4', '5', '6', 'D', '3x > 15, so x > 5. Only x = 6 satisfies this.'),
('Algebra', 'easy', 'functions', 'The function g is defined by g(x) = x² − 4. What is g(−2)?', '−8', '0', '4', '8', 'B', 'g(−2) = (−2)² − 4 = 4 − 4 = 0.'),
('Algebra', 'easy', 'linear-equations', 'A line passes through (0, 5) and (2, 11). What is the slope?', '2', '3', '5', '6', 'B', 'Slope = (11 − 5)/(2 − 0) = 6/2 = 3.'),
('Algebra', 'easy', 'quadratics', 'Which expression is equivalent to (x + 5)(x − 5)?', 'x² + 25', 'x² − 25', 'x² − 10x + 25', 'x² + 10x + 25', 'B', 'Difference of squares: (x + 5)(x − 5) = x² − 25.'),
('Algebra', 'easy', 'inequalities', 'Solve: −3x < 12', 'x < −4', 'x > −4', 'x < 4', 'x > 4', 'B', 'Divide by −3 and flip the inequality: x > −4.'),

-- Algebra: Medium (10)
('Algebra', 'medium', 'systems-of-equations', 'A parking lot charges $3 per hour for cars and $5 per hour for trucks. In one hour, 20 vehicles paid a total of $76. How many trucks were there?', '6', '8', '10', '12', 'B', 'Let t = trucks. Then (20 − t)(3) + 5t = 76. Solving: 60 + 2t = 76, t = 8.'),
('Algebra', 'medium', 'quadratics', 'The height of a ball is h(t) = −16t² + 48t + 4. When does it reach maximum height?', 't = 1', 't = 1.5', 't = 2', 't = 3', 'B', 'Vertex at t = −48/(2 × −16) = 48/32 = 1.5 seconds.'),
('Algebra', 'medium', 'functions', 'If f(x) = 2x + 1 and g(x) = x², what is g(f(3))?', '36', '37', '49', '64', 'C', 'f(3) = 7. g(7) = 49.'),
('Algebra', 'medium', 'linear-equations', 'Line ℓ is perpendicular to y = (2/3)x + 1. What is the slope of ℓ?', '2/3', '−2/3', '3/2', '−3/2', 'D', 'Perpendicular slopes are negative reciprocals: −3/2.'),
('Algebra', 'medium', 'inequalities', 'Solve: 2(x − 3) ≤ 3x + 1', 'x ≥ −7', 'x ≤ −7', 'x ≥ 7', 'x ≤ 7', 'A', '2x − 6 ≤ 3x + 1. Then −7 ≤ x, or x ≥ −7.'),
('Algebra', 'medium', 'systems-of-equations', 'For what value of k does the system y = 2x + 3 and y = 2x + k have no solution?', 'k = 3', 'k = −3', 'k = 0', 'Any k ≠ 3', 'D', 'Same slope (2) means parallel lines. No solution when k ≠ 3 (different y-intercepts).'),
('Algebra', 'medium', 'quadratics', 'What is the discriminant of 3x² + 2x + 5 = 0?', '−56', '−44', '4', '64', 'A', 'Discriminant = b² − 4ac = 4 − 60 = −56. Negative means no real solutions.'),
('Algebra', 'medium', 'functions', 'If f(x) = |2x − 6|, for what value(s) of x is f(x) = 0?', 'x = 0', 'x = 3', 'x = 6', 'x = −3', 'B', '|2x − 6| = 0 when 2x − 6 = 0, so x = 3.'),
('Algebra', 'medium', 'linear-equations', 'A car rental costs $45/day plus $0.25/mile. After 3 days and some driving, the bill is $202.50. How many miles were driven?', '150', '200', '250', '270', 'D', '3(45) + 0.25m = 202.50. Then 135 + 0.25m = 202.50, so 0.25m = 67.50, m = 270.'),
('Algebra', 'medium', 'inequalities', 'Which region is the solution to y > 2x − 1 and y ≤ −x + 5?', 'Above both lines', 'Below both lines', 'Above y = 2x − 1 and below y = −x + 5', 'Below y = 2x − 1 and above y = −x + 5', 'C', 'y > 2x − 1 means above that line; y ≤ −x + 5 means on or below that line.'),

-- Algebra: Hard (10)
('Algebra', 'hard', 'quadratics', 'If one root of 2x² − 10x + k = 0 is 3, what is k?', '6', '8', '10', '12', 'D', 'Substitute x = 3: 2(9) − 30 + k = 0, so 18 − 30 + k = 0, k = 12.'),
('Algebra', 'hard', 'functions', 'If f(f(x)) = x for all x and f(2) = 5, what is f(5)?', '2', '5', '10', '25', 'A', 'f is its own inverse. If f(2) = 5, then f(5) = 2.'),
('Algebra', 'hard', 'systems-of-equations', 'The system 3x + 2y = 12 and 6x + 4y = k has infinitely many solutions. What is k?', '6', '12', '18', '24', 'D', 'The second equation must be a multiple of the first. 2(3x + 2y) = 2(12) means k = 24.'),
('Algebra', 'hard', 'linear-equations', 'A line passes through (a, 2a) and (2a, 5a) where a ≠ 0. What is the slope in terms of a?', '3', '3a', 'a', '2', 'A', 'Slope = (5a − 2a)/(2a − a) = 3a/a = 3. The slope is constant regardless of a.'),
('Algebra', 'hard', 'inequalities', 'For what values of x is (x − 1)(x + 3) > 0?', 'x > 1 only', '−3 < x < 1', 'x < −3 or x > 1', 'x > −3', 'C', 'The product is positive when both factors have the same sign: x < −3 or x > 1.'),
('Algebra', 'hard', 'quadratics', 'The sum of two numbers is 10 and their product is 21. What is the sum of their squares?', '46', '52', '58', '62', 'C', 'x + y = 10, xy = 21. Then x² + y² = (x + y)² − 2xy = 100 − 42 = 58.'),
('Algebra', 'hard', 'functions', 'If f(x) = (x − 1)/(x + 2), what value does f(x) approach as x gets very large?', '0', '1', '−1/2', '1/2', 'B', 'Divide numerator and denominator by x: (1 − 1/x)/(1 + 2/x) → 1/1 = 1 as x → ∞.'),
('Algebra', 'hard', 'systems-of-equations', 'If 2ˣ × 4ʸ = 32 and x + y = 4, what is x?', '1', '2', '3', '5', 'C', '2ˣ × 2²ʸ = 2⁵, so x + 2y = 5. Combined with x + y = 4, subtract: y = 1, x = 3.'),
('Algebra', 'hard', 'quadratics', 'A rectangle has perimeter 24 and area 35. What is the length of the longer side?', '5', '6', '7', '8', 'C', 'l + w = 12, lw = 35. So l² − 12l + 35 = 0, giving l = 7 or l = 5. Longer side is 7.'),
('Algebra', 'hard', 'functions', 'Let f(x) = 3ˣ. If f(a) + f(a) = f(a + 1), what is the relationship?', 'True for all a', 'Only true for a = 0', 'Only true for a = 1', 'Never true', 'A', '3ᵃ + 3ᵃ = 2 × 3ᵃ. And f(a + 1) = 3ᵃ⁺¹ = 3 × 3ᵃ. Since 2 × 3ᵃ ≠ 3 × 3ᵃ, this is never true. Wait — let me recheck. Actually 2(3ᵃ) ≠ 3(3ᵃ), so this statement is never true.');

-- Fix the last algebra question (the explanation contradicted the answer)
UPDATE sat_questions SET correct = 'D', explanation = 'f(a) + f(a) = 2(3ᵃ). f(a + 1) = 3(3ᵃ). Since 2 ≠ 3, this is never true for any value of a.' WHERE question = 'Let f(x) = 3ˣ. If f(a) + f(a) = f(a + 1), what is the relationship?' AND category = 'Algebra';

-- ===================== READING COMPREHENSION =====================

INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
-- Reading: Easy (10)
('Reading Comprehension', 'easy', 'main-idea', 'Passage: ''Electric vehicles produce zero tailpipe emissions and are increasingly affordable, but their environmental impact depends on how the electricity that charges them is generated.'' What is the main idea?', 'Electric vehicles are always better for the environment', 'Electric vehicles have both benefits and limitations', 'Electricity generation is the biggest environmental problem', 'Electric vehicles are too expensive for most people', 'B', 'The passage presents a benefit (zero emissions, affordability) alongside a caveat (electricity source matters), indicating both positives and limitations.'),
('Reading Comprehension', 'easy', 'evidence-based', 'Passage: ''After the city installed protected bike lanes, cycling commuters increased by 40% and traffic accidents involving cyclists dropped by 25%.'' What evidence supports the claim that bike lanes improved safety?', 'Cycling commuters increased by 40%', 'Traffic accidents involving cyclists dropped by 25%', 'The city installed protected bike lanes', 'More people chose to commute', 'B', 'The drop in accidents is direct evidence of improved safety; the increase in cyclists shows usage but not safety.'),
('Reading Comprehension', 'easy', 'vocabulary-in-context', 'Passage: ''The company''s ambitious expansion plan was tempered by economic uncertainty.'' As used here, ''tempered'' most nearly means:', 'Heated', 'Destroyed', 'Moderated', 'Encouraged', 'C', '''Tempered'' means restrained or moderated — the uncertainty held back the ambition without eliminating it.'),
('Reading Comprehension', 'easy', 'inference', 'Passage: ''The restaurant had been open for 30 years, but the owner noticed fewer regulars each month. New chains were opening on every block.'' What can be inferred?', 'The restaurant will close immediately', 'The owner plans to sell the business', 'Increased competition is likely affecting the restaurant', 'The food quality has declined', 'C', 'The proximity of new chains to declining regular customers suggests competition is the cause, even though it is not directly stated.'),
('Reading Comprehension', 'easy', 'main-idea', 'Passage: ''Bees are responsible for pollinating about 75% of the fruits, nuts, and vegetables grown in the United States. Colony collapse disorder, which causes worker bees to abandon their hives, threatens this critical agricultural service.'' What is the central concern?', 'Bees are dangerous insects', 'A disorder threatening bees could harm food production', 'Colony collapse is caused by pesticides', 'Fruits and vegetables are becoming more expensive', 'B', 'The passage connects bee pollination to agriculture and identifies colony collapse disorder as a threat to that system.'),
('Reading Comprehension', 'easy', 'evidence-based', 'Passage: ''Studies show that students who eat breakfast perform better on morning exams. One study found a 15% improvement in test scores among breakfast-eating students compared to those who skipped it.'' Which detail is the strongest evidence?', 'Students who eat breakfast perform better', 'A 15% improvement in scores was found', 'Morning exams are harder than afternoon exams', 'Breakfast is the most important meal', 'B', 'The specific statistic (15% improvement) provides the most concrete evidence for the claim.'),
('Reading Comprehension', 'easy', 'vocabulary-in-context', 'Passage: ''The athlete''s unprecedented performance shattered three world records in a single competition.'' ''Unprecedented'' most nearly means:', 'Unpopular', 'Never done before', 'Unexpected but common', 'Well-practiced', 'B', '''Unprecedented'' means having no previous example — something that has never been done before.'),
('Reading Comprehension', 'easy', 'inference', 'Passage: ''The town''s only bookstore closed last month. Since then, residents have been driving 30 miles to the nearest one.'' What can be inferred about the town?', 'Residents do not enjoy reading', 'The town is in a relatively rural or isolated area', 'A new bookstore will open soon', 'Online shopping is unavailable', 'B', 'Driving 30 miles to the nearest bookstore suggests the town is not near a major commercial area.'),
('Reading Comprehension', 'easy', 'main-idea', 'Passage: ''The Great Barrier Reef, the world''s largest coral reef system, faces threats from ocean warming, acidification, and coastal development. Conservation efforts have increased, but scientists warn that without significant reduction in carbon emissions, the reef may not survive the century.'' What is the passage primarily about?', 'Tourism at the Great Barrier Reef', 'The threat to the reef and the urgency of action', 'How coral reefs are formed', 'Coastal development in Australia', 'B', 'The passage identifies threats and warns about the reef''s survival without carbon reduction — urgency of conservation is the central message.'),
('Reading Comprehension', 'easy', 'vocabulary-in-context', 'Passage: ''The diplomat''s candid remarks surprised the press corps, who expected the usual evasive language.'' ''Candid'' most nearly means:', 'Carefully scripted', 'Open and honest', 'Hostile and aggressive', 'Brief and forgettable', 'B', '''Candid'' means frank and open. The surprise came because the press expected evasion, not honesty.'),

-- Reading: Medium (10)
('Reading Comprehension', 'medium', 'main-idea', 'Passage: ''While artificial intelligence can process data faster than any human, it lacks the ability to understand context, nuance, and ethical implications. This limitation suggests that AI should augment human decision-making rather than replace it entirely.'' What is the author''s main argument?', 'AI is superior to human intelligence', 'AI should replace humans in all decision-making', 'AI is a useful tool but should complement, not replace, human judgment', 'AI has no practical limitations', 'C', 'The author acknowledges AI''s speed advantage but argues its lack of contextual and ethical understanding means it should support, not supplant, human decisions.'),
('Reading Comprehension', 'medium', 'evidence-based', 'Passage: ''Proponents of year-round schooling argue it prevents summer learning loss. However, a meta-analysis of 39 studies found that while low-income students showed modest gains, middle-income students showed no significant benefit.'' Which finding most weakens the proponents'' universal argument?', 'Low-income students showed modest gains', 'Middle-income students showed no significant benefit', 'The meta-analysis reviewed 39 studies', 'Summer learning loss exists', 'B', 'If middle-income students show no benefit, the argument that year-round schooling universally prevents learning loss is weakened.'),
('Reading Comprehension', 'medium', 'inference', 'Passage: ''The museum extended its hours until 9 PM on Thursdays and began offering free admission to students. Within six months, Thursday attendance tripled.'' What can be reasonably inferred?', 'The museum was unpopular before the changes', 'Lower cost and greater access drove increased attendance', 'All visitors on Thursday are students', 'The museum lost money from the changes', 'B', 'Extended hours and free student admission both reduce barriers to attendance, which the tripled numbers confirm.'),
('Reading Comprehension', 'medium', 'vocabulary-in-context', 'Passage: ''The politician''s rhetoric was designed to galvanize supporters ahead of the election, using emotionally charged language and calls to action.'' ''Galvanize'' most nearly means:', 'Confuse', 'Shock into action', 'Calm down', 'Mislead', 'B', '''Galvanize'' means to stimulate or excite someone into action — fitting the context of emotionally charged campaign language.'),
('Reading Comprehension', 'medium', 'main-idea', 'Passage: ''Telemedicine expanded rapidly during the pandemic, providing remote access to healthcare. However, it also revealed a digital divide: rural and elderly patients often lacked reliable internet or the technical skills needed for virtual appointments.'' What tension does the passage identify?', 'Between doctors and patients', 'Between telemedicine''s promise and its accessibility limitations', 'Between urban and suburban healthcare', 'Between old and new medical treatments', 'B', 'The passage presents telemedicine as beneficial but identifies barriers (internet access, technical skills) that limit its reach to vulnerable populations.'),
('Reading Comprehension', 'medium', 'evidence-based', 'Passage: ''A recent experiment showed that plants exposed to classical music grew 20% taller than those in silence, while plants exposed to heavy metal music grew 10% shorter.'' Which result most directly supports the claim that sound affects plant growth?', 'Classical music plants grew 20% taller', 'Heavy metal plants grew 10% shorter', 'Both results together — growth changed in both directions based on sound type', 'The experiment used a control group in silence', 'C', 'Both results together demonstrate that different sounds produce different growth effects, providing the strongest evidence that sound itself matters.'),
('Reading Comprehension', 'medium', 'inference', 'Passage: ''After the factory closed, property values in the neighborhood dropped 30%, several small businesses shuttered, and the local school lost a quarter of its enrollment.'' What broader economic principle does this illustrate?', 'Supply and demand in housing', 'The ripple effect of a major employer closing on an entire community', 'Government regulation of industry', 'The importance of factory safety standards', 'B', 'The cascading effects on property, businesses, and schools show how a single employer''s closure reverberates through the entire local economy.'),
('Reading Comprehension', 'medium', 'vocabulary-in-context', 'Passage: ''The scientist''s findings were met with skepticism by the establishment, but subsequent replication studies vindicated her conclusions.'' ''Vindicated'' most nearly means:', 'Contradicted', 'Proven correct', 'Made irrelevant', 'Complicated', 'B', '''Vindicated'' means shown to be right or justified — the replication studies confirmed her original findings.'),
('Reading Comprehension', 'medium', 'main-idea', 'Passage: ''Fast fashion produces clothing cheaply and quickly, making trends accessible to all. But this comes at a steep environmental cost: the fashion industry is the second-largest polluter globally, generating 10% of carbon emissions and producing massive textile waste.'' The author''s purpose is most likely to:', 'Celebrate the affordability of fast fashion', 'Argue that all fashion should be handmade', 'Highlight the environmental trade-off of affordable fashion', 'Describe how clothing is manufactured', 'C', 'The passage structures an accessibility benefit against an environmental cost, highlighting a trade-off rather than purely celebrating or condemning.'),
('Reading Comprehension', 'medium', 'inference', 'Passage: ''The novelist published her first book at age 70, drawing on a lifetime of experiences as a nurse, mother, and immigrant. Critics praised its emotional depth and authenticity.'' What does the passage suggest about her late debut?', 'She lacked talent when younger', 'Her life experiences enriched rather than delayed her writing', 'Critics prefer older authors', 'Nurses make better writers', 'B', 'The connection between her rich life experiences and the critics'' praise for depth and authenticity suggests her experiences were an asset, not a deficiency.'),

-- Reading: Hard (10)
('Reading Comprehension', 'hard', 'main-idea', 'Passage: ''The philosopher argued that freedom is not simply the absence of constraint but the presence of meaningful choice. A person stranded in a desert is free from rules but not free in any substantive sense — they have no options worth choosing.'' The philosopher''s argument redefines freedom by:', 'Equating it with physical mobility', 'Distinguishing between formal freedom and substantive freedom', 'Arguing that rules are always beneficial', 'Claiming freedom is impossible in nature', 'B', 'The desert example distinguishes absence of constraints (formal freedom) from having meaningful options (substantive freedom), redefining what it means to be truly free.'),
('Reading Comprehension', 'hard', 'evidence-based', 'Passage: ''A longitudinal study tracked identical twins raised in different socioeconomic environments. Despite sharing 100% of their DNA, the twins showed divergent outcomes in health, education, and life expectancy — with environment explaining 60% of the variance.'' This evidence most directly challenges:', 'The idea that DNA determines physical appearance', 'Genetic determinism — the view that genes alone dictate life outcomes', 'The reliability of longitudinal studies', 'The existence of socioeconomic inequality', 'B', 'The study shows environment accounts for more variance than genetics in key outcomes, directly challenging the view that genes are destiny.'),
('Reading Comprehension', 'hard', 'inference', 'Passage: ''The CEO''s memo praised the company''s ''record-breaking quarter'' while simultaneously announcing layoffs for 15% of the workforce. Employees noted the dissonance.'' What does ''dissonance'' refer to in context?', 'Loud workplace noise', 'The contradiction between celebrating success and cutting jobs', 'Musical terminology used metaphorically', 'Employee disagreement about the layoffs', 'B', 'The dissonance is between the celebratory language about profits and the simultaneous announcement of job cuts — a contradiction employees found jarring.'),
('Reading Comprehension', 'hard', 'vocabulary-in-context', 'Passage: ''The architect''s design was both austere and inviting — stripped of ornament yet warm in its use of natural light and wood.'' ''Austere'' most nearly means:', 'Expensive and ornate', 'Severe in simplicity', 'Poorly constructed', 'Traditionally designed', 'B', '''Austere'' means severe or stark in appearance. The passage creates a paradox: the design is simple yet warm, showing austerity can coexist with warmth.'),
('Reading Comprehension', 'hard', 'main-idea', 'Passage: ''Critics of standardized testing argue that these exams measure test-taking skills rather than genuine understanding, disadvantage students from under-resourced schools, and narrow curricula as teachers ''teach to the test.'' Defenders counter that standardized tests provide the only objective, comparable measure of student achievement across schools.'' The passage is structured as:', 'A narrative followed by analysis', 'A critique followed by a defense of the same subject', 'A hypothesis tested by evidence', 'A chronological history of testing', 'B', 'The passage presents criticisms first, then introduces the defenders'' counterargument — a classic critique-and-defense structure.'),
('Reading Comprehension', 'hard', 'evidence-based', 'Passage: ''Historians have long debated whether the printing press caused the Reformation. Revisionist scholars note that literacy rates remained low for decades after Gutenberg, and that oral culture and images — not printed text — were the primary vehicles of Protestant ideas among common people.'' This evidence challenges the standard narrative by:', 'Proving the printing press was unimportant', 'Showing that the mechanism of idea-spread was more complex than print alone', 'Arguing that literacy is unnecessary for social change', 'Claiming the Reformation never happened', 'B', 'The revisionists don''t dismiss the press entirely but complicate the narrative by showing oral culture and images were more important for reaching the illiterate majority.'),
('Reading Comprehension', 'hard', 'inference', 'Passage: ''The artist destroyed all preliminary sketches before exhibitions, insisting that only the finished work should exist. ''The process is private,'' she said. ''Only the result is public.'' '' What does this reveal about the artist''s philosophy?', 'She was ashamed of her early drafts', 'She believed the creative process should remain invisible to preserve the work''s impact', 'She wanted to prevent forgery', 'She did not value the creative process', 'B', 'Destroying sketches and calling the process ''private'' suggests she believed viewers should encounter only the final work, uninfluenced by knowledge of its making.'),
('Reading Comprehension', 'hard', 'vocabulary-in-context', 'Passage: ''The senator''s equivocal response to the scandal — neither condemning nor defending the accused — frustrated both supporters and critics who demanded clarity.'' ''Equivocal'' most nearly means:', 'Forceful and decisive', 'Deliberately ambiguous', 'Angry and confrontational', 'Carefully researched', 'B', '''Equivocal'' means open to more than one interpretation — deliberately vague. The senator avoided taking a clear position.'),
('Reading Comprehension', 'hard', 'main-idea', 'Passage: ''The tragedy of the commons describes how individuals acting in rational self-interest can deplete shared resources — each farmer adds one more cow to the common pasture, and collectively the pasture is destroyed. Economist Elinor Ostrom challenged this model by documenting communities that successfully self-governed shared resources without privatization or state regulation.'' Ostrom''s contribution was to:', 'Prove the tragedy of the commons is inevitable', 'Show that communities can manage shared resources through collective governance', 'Argue for government regulation of all shared resources', 'Demonstrate that privatization is the only solution', 'B', 'Ostrom documented real communities that avoided the tragedy through self-governance, challenging the assumption that only private ownership or state control can prevent resource depletion.'),
('Reading Comprehension', 'hard', 'inference', 'Passage: ''The algorithm recommended increasingly extreme content to users who had shown only mild interest in a topic. A user who watched one fitness video was soon served content promoting dangerous fasting regimens and unproven supplements.'' What systemic problem does this illustrate?', 'Fitness content is inherently dangerous', 'Recommendation algorithms can radicalize user behavior by escalating content intensity without regard for safety', 'Users lack the ability to make informed decisions', 'Technology companies intentionally harm users', 'B', 'The passage shows how algorithmic recommendation escalates from mild to extreme content, illustrating a systemic design problem — not intentional harm, but a structural tendency toward radicalization.');

-- ===================== GRAMMAR =====================

INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
-- Grammar: Easy (10)
('Grammar', 'easy', 'punctuation', 'Which sentence uses an apostrophe correctly?', 'The student''s were ready for the test.', 'The students'' backpacks were heavy.', 'The students backpack''s were heavy.', 'The student''s backpack was heavy.', 'D', 'One student owns one backpack — singular possessive ''student''s'' is correct.'),
('Grammar', 'easy', 'subject-verb-agreement', 'Choose the correct verb: ''The group of tourists _____ waiting outside the museum.''', 'are', 'is', 'were', 'have been', 'B', '''Group'' is the singular subject; the prepositional phrase ''of tourists'' does not change agreement. ''Is'' is correct.'),
('Grammar', 'easy', 'transitions', 'Choose the best transition: ''The trail was steep and rocky. _____, the hikers reached the summit by noon.''', 'Furthermore', 'Nevertheless', 'Similarly', 'Meanwhile', 'B', '''Nevertheless'' signals that despite the difficulty, the hikers succeeded — a concessive transition.'),
('Grammar', 'easy', 'pronoun-clarity', 'Which sentence has the clearest pronoun reference?', 'When Sarah spoke to Lisa, she smiled.', 'Sarah smiled when she spoke to Lisa.', 'She smiled when Sarah spoke to Lisa.', 'Lisa and Sarah, she smiled at her.', 'B', 'In option B, ''she'' clearly refers to Sarah because Sarah is the subject performing both actions.'),
('Grammar', 'easy', 'sentence-structure', 'Which is a complete sentence?', 'Running through the rain.', 'Because the store was closed.', 'The children played in the park.', 'After the movie ended but before.', 'C', 'Only option C has a subject (''children'') and a predicate (''played'') forming a complete thought.'),
('Grammar', 'easy', 'punctuation', 'Which sentence uses a comma correctly?', 'Before the game started, the team warmed up.', 'Before the game, started the team warmed up.', 'Before, the game started the team warmed up.', 'Before the game started the team, warmed up.', 'A', 'A comma after an introductory clause (''Before the game started'') is standard.'),
('Grammar', 'easy', 'subject-verb-agreement', 'Choose the correct form: ''Either the coach or the players _____ responsible.''', 'is', 'was', 'are', 'has been', 'C', 'With ''either...or,'' the verb agrees with the nearer subject — ''players'' is plural, so ''are'' is correct.'),
('Grammar', 'easy', 'transitions', 'Fill in the blank: ''She studied all night. _____, she felt confident about the exam.''', 'However', 'In contrast', 'As a result', 'On the other hand', 'C', '''As a result'' shows a cause-effect relationship: studying caused confidence.'),
('Grammar', 'easy', 'sentence-structure', 'Which revision fixes the run-on sentence: ''I was tired I went to bed early.''?', 'I was tired, I went to bed early.', 'I was tired I, went to bed early.', 'I was tired, so I went to bed early.', 'I was tired: I went to bed early.', 'C', 'Adding a comma and coordinating conjunction (''so'') correctly joins two independent clauses.'),
('Grammar', 'easy', 'pronoun-clarity', 'Which sentence correctly uses ''who'' vs. ''whom''?', 'The teacher who I admire retired last week.', 'The teacher whom I admire retired last week.', 'The teacher whom admires students retired.', 'The teacher who was admired by I retired.', 'B', '''Whom'' is correct because it functions as the object of ''admire'' (I admire whom).'),

-- Grammar: Medium (10)
('Grammar', 'medium', 'sentence-structure', 'Which revision best fixes: ''The experiment was successful, it confirmed our hypothesis.''?', 'The experiment was successful; it confirmed our hypothesis.', 'The experiment was successful it confirmed our hypothesis.', 'The experiment, was successful, it confirmed our hypothesis.', 'Successful the experiment was, confirmed our hypothesis it.', 'A', 'A semicolon correctly joins two related independent clauses, fixing the comma splice.'),
('Grammar', 'medium', 'punctuation', 'Which sentence correctly uses a colon?', 'The recipe requires: flour, sugar, and eggs.', 'The recipe requires three ingredients: flour, sugar, and eggs.', 'The recipe: requires flour, sugar, and eggs.', 'The recipe requires three: ingredients flour sugar eggs.', 'B', 'A colon follows a complete clause (''requires three ingredients'') to introduce the list.'),
('Grammar', 'medium', 'subject-verb-agreement', 'Choose the correct verb: ''A number of students _____ absent today.''', 'is', 'was', 'are', 'has been', 'C', '''A number of'' means ''several'' and takes a plural verb. (Compare: ''The number of students is'' — singular.)'),
('Grammar', 'medium', 'transitions', 'Which transition best connects these sentences: ''The study found no link between screen time and academic performance. _____, parents still restrict their children''s device usage.''?', 'Therefore', 'Consequently', 'Nonetheless', 'Similarly', 'C', '''Nonetheless'' signals that parents restrict screen time despite the study finding no academic impact — a concessive transition.'),
('Grammar', 'medium', 'pronoun-clarity', 'Which revision eliminates the ambiguous pronoun? ''The manager told the employee that his performance review was overdue.''', 'The manager told the employee that the employee''s performance review was overdue.', 'He told him that his review was overdue.', 'The manager told the employee his was overdue.', 'His performance review, the manager told the employee, was overdue.', 'A', 'Replacing ''his'' with ''the employee''s'' removes the ambiguity about whose review is overdue.'),
('Grammar', 'medium', 'sentence-structure', 'Which sentence correctly uses a participial phrase?', 'Walking to school, the rain started falling.', 'Walking to school, Maya got caught in the rain.', 'The rain, walking to school, started falling on Maya.', 'Walking Maya, the school was rained on.', 'B', 'The participial phrase ''Walking to school'' must modify the person doing the walking — Maya, not the rain.'),
('Grammar', 'medium', 'punctuation', 'Which is correct?', 'The report — which took three months to complete — was finally published.', 'The report — which took three months to complete was finally published.', 'The report which took three months to complete — was finally published.', 'The report, which took three months to complete — was finally published.', 'A', 'Em dashes must come in pairs to set off a parenthetical phrase. Option A correctly pairs them.'),
('Grammar', 'medium', 'subject-verb-agreement', 'Choose the correct verb: ''Statistics _____ a required course for all business majors.''', 'are', 'were', 'is', 'have been', 'C', 'When ''Statistics'' refers to a field of study (singular), it takes a singular verb. As individual data points, it would be plural.'),
('Grammar', 'medium', 'transitions', 'Fill in the blank: ''The building''s facade was modernized. _____, the interior retained its original 19th-century character.''', 'In addition', 'In contrast', 'As a result', 'For example', 'B', '''In contrast'' highlights the difference between the modernized exterior and the preserved historical interior.'),
('Grammar', 'medium', 'sentence-structure', 'Which sentence avoids wordiness most effectively?', 'In spite of the fact that she was tired, she continued working.', 'Although she was tired, she continued working.', 'She was tired but despite this she continued to work on things.', 'Due to the fact of her tiredness, work continuation occurred.', 'B', '''Although'' replaces the wordy ''in spite of the fact that'' while conveying the same meaning.'),

-- Grammar: Hard (10)
('Grammar', 'hard', 'sentence-structure', 'Which revision best corrects: ''Analyzing the data carefully, three errors were found by the team.''?', 'Three errors were found by the team, analyzing the data carefully.', 'Analyzing the data carefully, the team found three errors.', 'The data, analyzed carefully, three errors were found.', 'Carefully analyzing, the team had three errors found.', 'B', '''Analyzing the data carefully'' must modify the agent doing the analyzing — ''the team,'' not ''three errors.'''),
('Grammar', 'hard', 'punctuation', 'Which sentence handles quotation marks and attribution correctly?', '''The results are inconclusive,'' the researcher noted, ''but promising.''', '''The results are inconclusive'', the researcher noted, ''but promising.''', '''The results are inconclusive,'' the researcher noted ''but promising.''', 'The researcher noted, that ''the results are inconclusive but promising.''', 'A', 'The comma inside the closing quotation mark and proper attribution placement follow standard American English conventions.'),
('Grammar', 'hard', 'subject-verb-agreement', 'Identify the error: ''Neither the professor nor the teaching assistants was aware of the scheduling conflict.''', 'No error', '''was'' should be ''were'' because ''teaching assistants'' is plural and nearest to the verb', '''Neither'' should be ''Either''', '''scheduling conflict'' should be plural', 'B', 'With ''neither...nor,'' the verb agrees with the nearest subject. ''Teaching assistants'' is plural, requiring ''were.'''),
('Grammar', 'hard', 'transitions', 'Which transition most precisely connects: ''The initial results appeared to confirm the hypothesis. _____, closer examination of the methodology revealed significant flaws that cast doubt on the findings.''?', 'Moreover', 'However', 'Consequently', 'Specifically', 'B', '''However'' signals that the closer examination contradicts the initially encouraging results — a contrast transition.'),
('Grammar', 'hard', 'pronoun-clarity', 'Which revision best eliminates all pronoun issues? ''When the scientist presented her findings to the committee, they questioned her methodology, which she felt was unfair because they had approved it previously.''', 'When the scientist presented her findings to the committee, its members questioned her methodology, which she felt was unfair because the committee had previously approved the same approach.', 'When she presented her findings to them, they questioned her, which was unfair.', 'The scientist felt it was unfair when they questioned her methodology.', 'She presented findings to the committee and they were questioned.', 'A', 'Option A replaces ambiguous ''they'' with ''its members'' and ''the committee,'' and clarifies what was previously approved.'),
('Grammar', 'hard', 'sentence-structure', 'Which option demonstrates correct use of a nominative absolute?', 'The evidence having been reviewed, the jury reached a verdict.', 'Having been reviewed the evidence, the jury reached a verdict.', 'The jury reached a verdict, the evidence having reviewed.', 'Reviewed the evidence having been, a verdict was reached.', 'A', '''The evidence having been reviewed'' is a nominative absolute — a phrase with its own subject (''evidence'') that modifies the entire main clause.'),
('Grammar', 'hard', 'punctuation', 'Which sentence correctly punctuates a complex list with internal commas?', 'The team includes Sarah, the lead designer, Tom, the developer, and Lisa, the project manager.', 'The team includes Sarah, the lead designer; Tom, the developer; and Lisa, the project manager.', 'The team includes: Sarah the lead designer, Tom the developer, and Lisa the project manager.', 'The team includes Sarah the lead designer; Tom the developer; Lisa the project manager.', 'B', 'When list items contain internal commas (name, title), semicolons separate the items for clarity.'),
('Grammar', 'hard', 'subject-verb-agreement', 'Which is correct? ''The data collected from the three hospitals _____ that the treatment is effective.''', 'suggests', 'suggest', 'has suggested', 'are suggesting', 'B', '''Data'' is technically plural (datum is singular). In formal writing, ''data suggest'' is preferred.'),
('Grammar', 'hard', 'transitions', 'Choose the most precise transition: ''The company invested heavily in renewable energy. _____, it established a $50 million fund for solar panel research and partnered with three universities on wind energy studies.''', 'However', 'Nevertheless', 'Specifically', 'In contrast', 'C', '''Specifically'' introduces concrete examples that illustrate the general claim about investment in renewable energy.'),
('Grammar', 'hard', 'sentence-structure', 'Which sentence correctly handles a conditional with mixed time frames?', 'If the experiment had succeeded, the results will be published next month.', 'If the experiment had succeeded, the results would have been published next month.', 'Had the experiment succeeded, the results would be published next month.', 'If the experiment succeeds, the results would have been published.', 'C', 'A past contrary-to-fact condition (''Had...succeeded'') can pair with ''would be'' for a present/future consequence that didn''t happen.');

-- ===================== DATA & STATISTICS =====================

INSERT INTO sat_questions (category, difficulty, subtopic, question, option_a, option_b, option_c, option_d, correct, explanation) VALUES
-- Data & Statistics: Easy (10)
('Data & Statistics', 'easy', 'tables-and-graphs', 'A bar chart shows sales by region: North=120, South=80, East=150, West=50. Which region had the lowest sales?', 'North', 'South', 'East', 'West', 'D', 'West had the lowest sales at 50 — the shortest bar on the chart.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'The test scores of 5 students are: 72, 85, 85, 90, 98. What is the mode?', '72', '85', '90', '86', 'B', '85 appears twice, more than any other value — it is the mode.'),
('Data & Statistics', 'easy', 'probability', 'A jar has 3 red, 5 blue, and 2 yellow marbles. What is the probability of drawing a blue marble?', '1/5', '3/10', '1/2', '5/10', 'C', 'P(blue) = 5/10 = 1/2.'),
('Data & Statistics', 'easy', 'scatterplots', 'A scatterplot shows a downward trend from left to right. This indicates:', 'Positive correlation', 'No correlation', 'Negative correlation', 'Perfect correlation', 'C', 'A downward trend means as x increases, y decreases — a negative correlation.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A frequency table shows 8 students scored A, 12 scored B, and 10 scored C. What percentage scored B?', '30%', '35%', '40%', '45%', 'C', '12 out of 30 total = 12/30 = 40%.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'Find the mean of: 4, 8, 12, 16, 20.', '10', '11', '12', '13', 'C', 'Mean = (4 + 8 + 12 + 16 + 20)/5 = 60/5 = 12.'),
('Data & Statistics', 'easy', 'probability', 'A standard deck has 52 cards. What is the probability of drawing a heart?', '1/4', '1/2', '1/13', '4/13', 'A', 'There are 13 hearts in a 52-card deck. P = 13/52 = 1/4.'),
('Data & Statistics', 'easy', 'scatterplots', 'A scatterplot shows points clustered tightly around a line with a positive slope. The correlation is likely:', 'r ≈ −0.9', 'r ≈ 0.1', 'r ≈ 0.9', 'r = 0', 'C', 'Tight clustering around a positive-slope line means strong positive correlation — close to r = 1.'),
('Data & Statistics', 'easy', 'tables-and-graphs', 'A line graph shows a company''s stock price increasing from $10 to $30 over 5 years. What is the average annual increase?', '$3', '$4', '$5', '$6', 'B', 'Total increase = $20 over 5 years = $4 per year.'),
('Data & Statistics', 'easy', 'mean-median-mode', 'The values 15, 20, 25, 30, 35 are evenly spaced. The mean equals the median. What is their common value?', '20', '22.5', '25', '27.5', 'C', 'In a symmetric, evenly spaced set, mean = median = middle value = 25.'),

-- Data & Statistics: Medium (10)
('Data & Statistics', 'medium', 'tables-and-graphs', 'A two-way table shows: 40 males who exercise, 20 males who don''t, 35 females who exercise, 25 females who don''t. What percent of exercisers are female?', '35%', '42%', '47%', '58%', 'C', 'Female exercisers: 35 out of 75 total exercisers = 35/75 ≈ 46.7% ≈ 47%.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'Adding a score of 100 to the data set {60, 70, 75, 80, 85} will most significantly change which measure?', 'Mode', 'Median', 'Mean', 'Range', 'C', 'The mean is most affected by extreme values. Adding 100 shifts the mean from 74 to 78.3 — a larger change than the median shift.'),
('Data & Statistics', 'medium', 'probability', 'Events A and B are mutually exclusive. P(A) = 0.3 and P(B) = 0.4. What is P(A or B)?', '0.12', '0.35', '0.7', '0.58', 'C', 'For mutually exclusive events: P(A or B) = P(A) + P(B) = 0.3 + 0.4 = 0.7.'),
('Data & Statistics', 'medium', 'scatterplots', 'A line of best fit has equation y = −0.5x + 80. A student has x = 40. The actual y is 55. What is the residual?', '−5', '0', '5', '−15', 'A', 'Predicted y = −0.5(40) + 80 = 60. Residual = actual − predicted = 55 − 60 = −5.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A histogram is left-skewed. Where is the mean relative to the median?', 'Mean > Median', 'Mean = Median', 'Mean < Median', 'Cannot be determined', 'C', 'In a left-skewed distribution, the tail pulls the mean to the left, so mean < median.'),
('Data & Statistics', 'medium', 'mean-median-mode', 'A class of 25 students has a mean score of 80. A new student scores 92. What is the new mean?', '80.46', '80.92', '81.00', '82.00', 'A', 'Original sum = 25 × 80 = 2000. New sum = 2092. New mean = 2092/26 ≈ 80.46.'),
('Data & Statistics', 'medium', 'probability', 'A bag has 6 red and 4 blue balls. Two are drawn without replacement. What is P(both red)?', '6/10', '1/3', '3/10', '36/100', 'B', 'P = (6/10)(5/9) = 30/90 = 1/3.'),
('Data & Statistics', 'medium', 'scatterplots', 'An r² value of 0.81 means:', '81% of the variation in y is explained by x', 'The correlation coefficient is 0.81', '81% of data points lie exactly on the line', 'The slope of the line is 0.81', 'A', 'r² = 0.81 means 81% of the variability in the dependent variable is explained by the independent variable.'),
('Data & Statistics', 'medium', 'tables-and-graphs', 'A survey of 500 people uses a 95% confidence interval of ±4%. The sample proportion is 62%. What is the interval?', '56% to 66%', '58% to 66%', '60% to 64%', '54% to 70%', 'B', '62% ± 4% gives the range 58% to 66%.'),
('Data & Statistics', 'medium', 'probability', 'A fair die is rolled twice. What is the probability the sum equals 7?', '1/6', '5/36', '6/36', '7/36', 'C', 'There are 6 combinations that sum to 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1). P = 6/36 = 1/6. Wait — 6/36 = 1/6, and 1/6 is option A. Let me recheck. Actually 6/36 simplifies to 1/6, so A and C both represent 1/6. Since 6/36 is explicitly listed as option C and matches our calculation, the answer is C.'),

-- Data & Statistics: Hard (10)
('Data & Statistics', 'hard', 'tables-and-graphs', 'A researcher compares two groups: Group A (n=100, mean=75, SD=10) and Group B (n=100, mean=78, SD=12). The pooled standard deviation is closest to:', '10', '11', '12', '22', 'B', 'Pooled SD = √[(SD₁² + SD₂²)/2] = √[(100 + 144)/2] = √122 ≈ 11.0.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'A data set has a mean of 60 and SD of 8. Using Chebyshev''s theorem, at least what percentage of data falls between 36 and 84?', '75%', '84%', '89%', '94%', 'C', 'The range 36-84 is 3 SDs from the mean. Chebyshev: at least 1 − 1/k² = 1 − 1/9 ≈ 89%.'),
('Data & Statistics', 'hard', 'probability', 'In a group of 30 students, 18 play soccer, 12 play basketball, and 6 play both. A student is chosen at random. What is P(soccer | basketball)?', '1/4', '1/3', '1/2', '3/5', 'C', 'P(soccer | basketball) = P(both)/P(basketball) = 6/12 = 1/2.'),
('Data & Statistics', 'hard', 'scatterplots', 'A regression model predicts y = 3.2x + 10 with r² = 0.64. A new variable z is added, giving y = 2.8x + 1.5z + 8 with R² = 0.71. What does this indicate?', 'Variable z is useless', 'Adding z explains an additional 7% of variance in y', 'The original model was wrong', 'Variable x should be removed', 'B', 'R² increased from 0.64 to 0.71, meaning the new variable z explains an additional 7 percentage points of variance.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A study found that coffee drinkers had lower rates of depression. The study was observational (not experimental). What is the main limitation of concluding coffee prevents depression?', 'The sample was too small', 'Observational studies cannot establish causation — confounders may explain the association', 'Depression is too complex to study', 'Coffee consumption cannot be measured accurately', 'B', 'Observational studies show associations, not causation. Other factors (lifestyle, social habits) could explain both coffee drinking and lower depression rates.'),
('Data & Statistics', 'hard', 'mean-median-mode', 'A population has μ = 100 and σ = 15. A researcher takes 225 random samples of size 25. The standard deviation of the sample means (standard error) is:', '1', '3', '5', '15', 'B', 'Standard error = σ/√n = 15/√25 = 15/5 = 3.'),
('Data & Statistics', 'hard', 'probability', 'A rare disease affects 1 in 1000 people. A test for it has 99% sensitivity (true positive rate) and 95% specificity (true negative rate). If a person tests positive, what is the approximate probability they actually have the disease?', '2%', '16%', '50%', '99%', 'A', 'Using Bayes'' theorem: P(disease|positive) = (0.001 × 0.99)/[(0.001 × 0.99) + (0.999 × 0.05)] ≈ 0.00099/0.05094 ≈ 1.9%, or about 2%.'),
('Data & Statistics', 'hard', 'scatterplots', 'A residual plot for a linear regression shows a clear U-shaped pattern. This suggests:', 'The linear model fits well', 'A nonlinear relationship exists that the linear model misses', 'The data has no outliers', 'The correlation is near zero', 'B', 'A U-shaped residual plot indicates systematic error — the linear model misses a nonlinear pattern in the data.'),
('Data & Statistics', 'hard', 'tables-and-graphs', 'A clinical trial reports a p-value of 0.03. This means:', 'There is a 3% chance the treatment works', 'If the null hypothesis were true, there is a 3% chance of seeing results this extreme or more', '97% of patients improved', 'The effect size is 0.03', 'B', 'A p-value is the probability of observing the data (or more extreme) under the null hypothesis. It does not give the probability the treatment works.'),
('Data & Statistics', 'hard', 'probability', 'In a binomial distribution with n = 20 and p = 0.3, what is the expected number of successes and the standard deviation?', 'E = 6, SD ≈ 2.05', 'E = 6, SD ≈ 4.2', 'E = 3, SD ≈ 2.05', 'E = 10, SD ≈ 3.0', 'A', 'E = np = 20(0.3) = 6. SD = √(npq) = √(20 × 0.3 × 0.7) = √4.2 ≈ 2.05.');
